import 'package:flutter/material.dart';

/// Lightweight in-app localization for Arabic and English.
class AppLocalizations {
  AppLocalizations._();

  static const String _fallbackLanguage = 'en';

  /// Every key defined for a language. Used by the tests that keep the two
  /// dictionaries in step and catch a `tr` call with no entry behind it.
  static Set<String> keysFor(String languageCode) =>
      (_localizedValues[languageCode] ?? const {}).keys.toSet();

  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      // Imsakiya poster: weekday names and captions.
      'weekday': 'Day',
      'weekday_sunday': 'Sunday',
      'weekday_monday': 'Monday',
      'weekday_tuesday': 'Tuesday',
      'weekday_wednesday': 'Wednesday',
      'weekday_thursday': 'Thursday',
      'weekday_friday': 'Friday',
      'weekday_saturday': 'Saturday',
      'ramadan_month': 'Ramadan',
      'imsakiya_footer':
          'Calculated on your device for your own location — Islamic App.',
      // Seasonal theme, qibla compass, location picking.
      'last_read_position': 'Verse {verse} of {total} · page {page}',
      'season_ramadan_greeting': 'Ramadan Kareem',
      'season_ramadan_subtitle':
          'A month of Quran — your wird, the timetable, and the nights are all here.',
      'season_last_ten_greeting': 'The last ten nights',
      'season_last_ten_subtitle':
          'Laylat al-Qadr is sought in the odd nights — strive in all of them.',
      'season_eid_fitr_greeting': 'Eid Mubarak',
      'season_eid_fitr_subtitle': 'May Allah accept from us and from you.',
      'season_eid_adha_greeting': 'Eid Adha Mubarak',
      'season_eid_adha_subtitle':
          'The days of Tashreeq: remembrance, takbir, and gratitude.',
      'qibla_no_sensor': 'This device has no compass sensor.',
      'qibla_calibrate':
          'Compass accuracy is low — move the phone in a figure of eight.',
      'location_settings': 'Location',
      'location_settings_desc':
          'Follow the device, or pin a city and keep its times.',
      'location_automatic': 'Use my current location',
      'location_automatic_desc': 'Switch back to following the device.',
      'location_search': 'Search for a city',
      'location_search_hint': 'Cairo, Riyadh, Istanbul…',
      'location_no_results': 'No place matched that name.',
      'location_unknown': 'Location not set yet',
      'location_resolving': 'Finding your location…',
      'location_pinned': 'Pinned manually — times follow this place.',
      // Phase 4: page mode, memorisation, backup, Ramadan, downloads.
      'reader_view_mode': 'Layout',
      'view_continuous': 'Continuous',
      'view_pages': 'Pages',
      'hifz': 'Memorisation',
      'hifz_add': 'Add a passage',
      'hifz_add_verse': 'Memorise',
      'hifz_added': 'Added to your memorisation list.',
      'hifz_empty':
          'Nothing here yet. Add a passage and it will come back for review on a schedule that widens as you hold it.',
      'hifz_all': 'Everything you are memorising',
      'hifz_due_today': 'Due today',
      'hifz_due_desc': 'Recall each passage, then grade yourself honestly.',
      'hifz_nothing_due': 'Nothing due — come back tomorrow.',
      'hifz_start_review': 'Start reviewing',
      'hifz_due_now': 'Due now',
      'hifz_next_review': 'Next review',
      'tasbeeh_mode_rounds': 'Rounds of 33',
      'tasbeeh_mode_endless': 'Endless',
      'tasbeeh_lifetime': 'Total count',
      'tasbeeh_today': 'Today',
      'tasbeeh_endless_reset_title': 'Clear the total?',
      'tasbeeh_endless_reset_body':
          'The endless count is kept forever and never resets on its own. Clearing it cannot be undone.',
      'preview_unavailable':
          'This sound belongs to the system and cannot be played here — it will still sound at prayer time.',
      'recite_voice_pack': 'Voice pack',
      'recite_voice_pack_desc':
          'Which installed pack listens to your recitation. Any Arabic pack works — pick whichever hears you best.',
      'recite_pack_automatic': 'Automatic',
      'recite_pack_automatic_desc': 'Use the best Arabic pack on this device',
      'recite_no_arabic_pack':
          'No Arabic voice pack is installed on this device yet. The rest of the app works without one — download a pack only if you want the recitation check.',
      'recite_download_pack': 'Download a pack',
      'recite_download_hint':
          'Opens your device settings. Look for offline speech or voice input, then add Arabic — you can install several and switch between them here.',
      'recite_settings_unavailable':
          'This device has no screen for downloading voice packs.',
      'recite_show_other_packs': 'Show other languages',
      'recite_hide_other_packs': 'Hide other languages',
      'done': 'Done',
      'stt_offline_engines': 'Offline engines',
      'stt_offline_engines_desc':
          'Recognition that runs on your phone with no Google and no network. Optional — download one only if you want it, and delete it whenever you like.',
      'stt_model_tiny': 'Whisper Tiny — multilingual',
      'stt_model_base': 'Whisper Base — multilingual',
      'stt_model_small': 'Whisper Small — multilingual',
      'stt_download_confirm':
          'Downloads {download} and uses about {installed} on your device once unpacked. It works fully offline afterwards, and you can delete it at any time.',
      'stt_download_failed': 'The download did not finish. Nothing was kept.',
      'stt_extracting': 'Unpacking…',
      'downloading': 'Downloading',
      'delete': 'Delete',
      'recite_mode_check': 'Check my memory',
      'recite_mode_identify': 'Which verse is this?',
      'recite_identify_hint':
          'Recite anything and the app will find it in the Mushaf — offline, from the bundled text.',
      'recite_identify_none':
          'That does not match anything in the Mushaf. Try a few more words.',
      'category_word': 'categories',
      'zekr_word': 'dhikr',
      'greeting_morning': 'Good morning',
      'greeting_afternoon': 'Peace be upon you',
      'greeting_evening': 'Good evening',
      'ayah_of_day': 'Verse of the day',
      'mark_prayed': 'Mark as prayed',
      'minute_short': 'min',
      'kilometre_short': 'km',
      'qibla_bearing': 'Bearing',
      'qibla_distance': 'To the Kaaba',
      'qibla_angle_caption': 'Off the qibla',
      'qibla_turn_left': 'Turn the phone {degrees}° to the left',
      'qibla_turn_right': 'Turn the phone {degrees}° to the right',
      'design_gallery': 'Component gallery',
      'design_gallery_desc':
          'Every piece of the design system on one screen. Switch mood and season here to check a pairing in seconds instead of on the day it ships.',
      'design_gallery_glass':
          'Glass needs something scrolling underneath it, or it is just a grey rectangle.',
      'seasonal_preview': 'Preview seasons',
      'seasonal_preview_desc':
          'Wear any season on any day to check its colours, banner and opening before it arrives. The app stays dressed for it until you switch back to automatic.',
      'seasonal_preview_auto': 'Automatic (by the Hijri date)',
      'seasonal_preview_auto_none':
          'No season today — the app wears its usual colours.',
      'seasonal_preview_has_intro': 'Has an opening film',
      'seasonal_preview_no_intro': 'No opening film yet',
      'seasonal_preview_play': 'Play the opening',
      'seasonal_preview_live': 'Live preview',
      'seasonal_preview_active': 'Season preview is on',
      'seasonal_preview_exit': 'Back to automatic',
      'recite_title': 'Recitation check',
      'recite_start': 'Start reciting',
      'recite_stop': 'Stop',
      'recite_experimental':
          'Experimental: the device recognizer is not built for classical recitation, so treat this as a reading aid, not a ruling.',
      'recite_progress': 'Reached',
      'recite_heard': 'What was heard',
      'recite_legend_ok': 'Correct',
      'recite_legend_near': 'Close',
      'recite_legend_wrong': 'Check again',
      'recite_no_permission':
          'Microphone permission is needed to check your recitation.',
      'recite_no_arabic':
          'No Arabic speech pack on this device. Install one from the system settings.',
      'recite_unavailable':
          'Speech recognition is not available on this device.',
      'recite_failed': 'Listening could not start. Try again.',
      'intro_skip': 'Skip',
      'seasonal_intro': 'Seasonal opening',
      'seasonal_intro_desc':
          'Play a short Ramadan or Eid intro once a day when the app opens.',
      'hifz_review': 'Review',
      'hifz_mask_hidden': 'Hidden',
      'hifz_mask_letters': 'First letters',
      'hifz_mask_none': 'Visible',
      'hifz_tap_word': 'Tap any word to reveal it.',
      'hifz_how_was_it': 'How did that go?',
      'hifz_grade_again': 'Again',
      'hifz_grade_good': 'Good',
      'hifz_grade_easy': 'Easy',
      'hifz_quiz': 'Finish the verse',
      'quiz_prompt': 'Which verse comes next?',
      'quiz_score': 'Score',
      'quiz_next': 'Next',
      'quiz_restart': 'Play again',
      'backup': 'Backup',
      'backup_desc': 'Export everything to a file, or restore it.',
      'backup_explain':
          'Bookmarks, notes, the reading log, memorisation, and every setting — in one file you keep.',
      'backup_export': 'Export a backup',
      'backup_export_desc': 'Share it to Drive, mail, or anywhere else.',
      'backup_import': 'Restore from a file',
      'backup_import_desc': 'Entries with the same key are replaced.',
      'backup_restored': 'Backup restored.',
      'backup_invalid': 'That file is not a backup from this app.',
      'backup_newer_version':
          'That backup was made by a newer version of the app.',
      'ramadan_day': 'Ramadan {day}',
      'ramadan_until_iftar': 'Until iftar',
      'ramadan_until_imsak': 'Until imsak',
      'tarawih_tonight': 'Tonight\'s tarawih',
      'tarawih_mark': 'Mark done',
      'tarawih_done': 'Done',
      'reciter_library': 'Reciters and downloads',
      'download': 'Download',
      'downloaded_offline': 'Available offline',
      'downloads_size': 'Storage used',
      'downloads_clear': 'Delete all',
      'downloads_delete': 'Delete',
      // Imsakiya, the last ten nights, azkar cards.
      'zekr_done': 'Done',
      'zekr_tap_to_count': 'Tap to count',
      'imsakiya': 'Ramadan timetable',
      'imsakiya_desc':
          'Imsak, Fajr, and iftar for every day of the month, from your own location.',
      'imsakiya_note':
          'Imsak is printed ten minutes before Fajr, as timetables traditionally do.',
      'imsakiya_day': 'Day',
      'imsakiya_unavailable': 'The timetable needs your location.',
      'imsak': 'Imsak',
      'iftar': 'Iftar',
      'event_laylat_qadr_expected': 'Laylat al-Qadr is hoped for tonight',
      'event_last_ten': 'One of the last ten nights',
      'event_odd_night': 'An odd night of the last ten',
      'laylat_qadr_note':
          'Laylat al-Qadr is sought across the odd nights of the last ten — the 27th is the most likely in the reports, not a certainty. Strive in all of them.',
      // Phase 3: adhan sounds, khatmah, daily wird, stats, occasions.
      'adhan_sound_rifat': 'Cairo adhan — Muhammad Rifat',
      'adhan_sound_mustafa_ismail': 'Adhan — Mustafa Ismail',
      'adhan_sound_fajr_abu_rahiq': 'Fajr adhan — Ibrahim Abu Rahiq',
      'adhan_sound_custom': 'Your adhan',
      'adhan_sound_custom_desc': 'A file you added',
      'adhan_sound_saved': 'Adhan saved.',
      'import_adhan': 'Add an audio file',
      'pick_device_sound': 'Pick from the device',
      'preview_sound': 'Hear it',
      'adhan_import_unsupported':
          'Adding a file needs Android 10 or newer. You can still pick a sound already on the device.',
      'adhan_import_failed': 'Could not add that file. Try another one.',
      'fajr_adhan_sound': 'A different adhan for Fajr',
      'fajr_adhan_sound_desc':
          'The Fajr call has its own extra line, so many people prefer a separate recording.',
      'narrated_by': 'Narrated by',
      'khatmah_plan': 'Khatmah plan',
      'khatmah_plan_desc':
          'Pick how long you want the Mushaf to take; the daily portion is worked out for you.',
      'khatmah_in_days': 'In {days} days',
      'khatmah_custom': 'Custom',
      'khatmah_days_label': 'Number of days',
      'khatmah_progress': '{read} of {total} pages',
      'khatmah_ahead': 'You are {pages} pages ahead.',
      'khatmah_behind':
          'You are {pages} pages behind — today’s portion covers it.',
      'khatmah_cancel': 'End plan',
      'khatmah_completed': 'You finished the Mushaf. May Allah accept it.',
      'khatmah_start_new': 'Start a new khatmah',
      'khatmah_day_of': 'Day {day} of {days}',
      'today_portion': 'Today\'s portion',
      'today_read': 'Read today',
      'days_left': 'Days left',
      'pages_count': '{count} pages',
      'reading_stats': 'Reading stats',
      'reading_streak': 'Streak',
      'reading_streak_desc': 'Consecutive days with at least one page read.',
      'current_streak': 'Current',
      'longest_streak': 'Longest',
      'today_read_pages': 'Today: {count} pages',
      'reading_totals': 'Totals',
      'days_read': 'Days',
      'pages_read': 'Pages',
      'time_read': 'Time',
      'this_week': 'This week',
      'reading_year': 'The year',
      'reading_year_desc':
          'One square per day; the darker it is, the more you read.',
      'daily_wird': 'Daily wird',
      'wird_quran': 'Quran portion',
      'wird_morning_azkar': 'Morning azkar',
      'wird_evening_azkar': 'Evening azkar',
      'wird_tasbeeh': 'Tasbeeh',
      'wird_done_of': '{done} of {total}',
      'wird_unavailable': 'The wird is unavailable right now.',
      'occasion_reminders': 'Occasions and fasting',
      'occasion_reminders_desc':
          'Friday, the recommended fasting days, and the Hijri occasions.',
      'friday_reminder': 'Friday reminder',
      'friday_reminder_desc': 'Surah Al-Kahf, an hour after Fajr.',
      'fasting_reminder': 'Fasting reminder',
      'fasting_reminder_desc':
          'The night before Monday, Thursday, and the white days.',
      'islamic_events': 'Hijri occasions',
      'islamic_events_desc':
          'Ashura, Arafah, the two Eids, Ramadan, and the white days.',
      'notif_kind_event': 'Occasion',
      'notif_friday_title': 'Friday',
      'notif_friday_body':
          'Read Surah Al-Kahf and send salawat upon the Prophet ﷺ.',
      'notif_event_body': 'Open the calendar to see what today is.',
      'notif_event_fasting_body': 'A recommended day to fast.',
      'notif_fasting_title': 'Fasting tomorrow?',
      'notif_fasting_body':
          'Tomorrow is Monday or Thursday — a day of fasting.',
      'notif_fasting_white_body': 'Tomorrow is one of the white days.',
      'widget_in_hours': 'in {hours}h {minutes}m',
      'widget_in_minutes': 'in {minutes} minutes',
      // Index modes, notes, player, prayer tuning, Hijri calendar, adhan sounds.
      'hizb_tab': 'Hizb',
      'pages_tab': 'Pages',
      'sajdah_tab': 'Sajdah',
      'hizb_index': 'Hizb Index',
      'pages_index': 'Page Index',
      'sajdah_index': 'Sajdah verses',
      'sajdah_word': 'Sajdah',
      'starts_at': 'Starts at',
      'search_hizb_hint': 'Search hizb number…',
      'search_page_hint': 'Search page number…',
      'jump_to': 'Go to',
      'invalid_reference': 'That reference does not exist.',
      'open': 'Open',
      'no_results': 'No results.',
      'my_reflections': 'My reflections',
      'no_notes_yet':
          'No notes yet. Open a verse, choose "Add a note", and it appears here.',
      'search_notes_hint': 'Search your notes…',
      'export_notes': 'Export',
      'sort': 'Sort',
      'sort_newest': 'Newest first',
      'sort_mushaf': 'Mushaf order',
      'open_in_reader': 'Open in the reader',
      'player': 'Player',
      'play': 'Play',
      'pause': 'Pause',
      'stop': 'Stop',
      'playback_speed': 'Playback speed',
      'repeat_verse': 'Repeat the verse',
      'repeat_verse_desc': 'Keeps looping the verse being recited.',
      'repeat_range': 'Repeat a range',
      'repeat_range_desc':
          'Pick the first and last verse, and how many times to repeat them.',
      'range_from': 'From',
      'range_to': 'To',
      'repeat_times': 'Repetitions',
      'repeat_endless': 'Endless',
      'start_repeat': 'Start repeating',
      'sleep_timer': 'Sleep timer',
      'end_of_passage': 'End of passage',
      'minutes_short': 'min',
      'prayer_calculation_settings': 'Prayer time settings',
      'today_preview': 'Today\'s times',
      'asr_madhab': 'Asr calculation',
      'asr_madhab_desc': 'Hanafi uses a longer shadow, so Asr comes later.',
      'madhab_shafi': 'Shafi / Maliki / Hanbali',
      'madhab_hanafi': 'Hanafi',
      'high_latitude_rule': 'High latitude rule',
      'high_latitude_desc':
          'Used where the sun does not dip far enough for Fajr and Isha.',
      'high_lat_middle_of_the_night': 'Middle of the night',
      'high_lat_seventh_of_the_night': 'One seventh of the night',
      'high_lat_twilight_angle': 'Twilight angle',
      'manual_offsets': 'Manual adjustment',
      'manual_offsets_desc':
          'Shift any prayer by a few minutes to match your local mosque.',
      'reset_offsets': 'Clear adjustments',
      'hijri_adjustment': 'Hijri correction',
      'hijri_adjustment_desc':
          'Move the Hijri date by a day if your country sights the moon differently.',
      'hijri_calendar': 'Hijri calendar',
      'hijri_calendar_desc':
          'The Islamic month with its events, fasting days, and prayer times.',
      'day_sun': 'Sun',
      'day_mon': 'Mon',
      'day_tue': 'Tue',
      'day_wed': 'Wed',
      'day_thu': 'Thu',
      'day_fri': 'Fri',
      'day_sat': 'Sat',
      'event_islamic_new_year': 'Islamic New Year',
      'event_ashura': 'Ashura',
      'event_mawlid': 'The Prophet’s birthday',
      'event_isra_miraj': 'Isra and Miraj',
      'event_mid_shaban': 'Mid-Shaban',
      'event_ramadan_start': 'First of Ramadan',
      'event_laylat_qadr': 'Laylat al-Qadr (27th)',
      'event_eid_fitr': 'Eid al-Fitr',
      'event_arafah': 'Day of Arafah',
      'event_eid_adha': 'Eid al-Adha',
      'event_tashreeq': 'Days of Tashreeq',
      'event_white_days': 'White days',
      'event_monday_thursday': 'A recommended fasting day (Monday/Thursday)',
      'adhan_sound': 'Adhan sound',
      'adhan_sound_desc': 'Plays for prayers set to the Adhan mode.',
      'adhan_sound_system': 'Default notification sound',
      'adhan_sound_makkah': 'Makkah adhan',
      'adhan_sound_madinah': 'Madinah adhan',
      'adhan_sound_alafasy': 'Alafasy adhan',
      'adhan_sound_missing': 'Audio file not bundled yet',
      'adhan_sound_hint':
          'To enable an adhan, add its audio file to android/app/src/main/res/raw/ and list its id in NotificationService.bundledAdhanSoundIds.',
      // Phase 1 & 2: notification centre, reader controls, bookmarks, tafsir.
      'notification_center': 'Notification Centre',
      'notification_center_desc':
          'Every reminder in one place, with a preview of what will actually arrive.',
      'notif_master': 'Enable reminders',
      'notif_master_desc': 'Schedules the coming week on this device.',
      'notif_scheduled_count': '{count} reminders queued',
      'notif_none_scheduled': 'Nothing scheduled yet.',
      'notif_reschedule': 'Reschedule',
      'notif_exact_alarms_missing':
          'Exact alarms are off, so reminders may arrive a few minutes late.',
      'notif_allow_exact_alarms': 'Allow exact alarms',
      'send_test': 'Send a test',
      'prayer_alerts': 'Prayer alerts',
      'prayer_alerts_desc': 'Pick how each prayer announces itself.',
      'apply_to_all': 'All prayers',
      'mode_off': 'Off',
      'mode_silent': 'Silent',
      'mode_vibrate': 'Vibrate',
      'mode_notification': 'Notification',
      'mode_adhan': 'Adhan',
      'pre_adhan_reminder': 'Before the adhan',
      'pre_adhan_desc': 'A heads-up so you can get ready for the prayer.',
      'iqama_reminder': 'Iqama reminder',
      'iqama_desc': 'Sent after the adhan, at your local iqama gap.',
      'minutes_off': 'Off',
      'minutes_value': '{minutes} min',
      'azkar_reminders': 'Azkar reminders',
      'azkar_reminders_desc': 'Anchored to the sun, not to a fixed clock time.',
      'morning_azkar_reminder': 'Morning azkar',
      'evening_azkar_reminder': 'Evening azkar',
      'offset_after_fajr': 'After Fajr',
      'offset_after_asr': 'After Asr',
      'daily_reminders': 'Daily reminders',
      'daily_ayah_reminder': 'Verse of the day',
      'wird_reminder': 'Daily wird',
      'change_time': 'Change time',
      'quiet_hours': 'Quiet hours',
      'quiet_hours_desc':
          'Mutes the optional reminders. Prayer alerts are never silenced.',
      'quiet_from': 'From',
      'quiet_to': 'To',
      'upcoming_alerts': 'Coming up',
      'today': 'Today',
      'tomorrow': 'Tomorrow',
      'notif_kind_prayer': 'Prayer',
      'notif_kind_pre': 'Before adhan',
      'notif_kind_iqama': 'Iqama',
      'notif_kind_azkar': 'Azkar',
      'notif_kind_ayah': 'Verse',
      'notif_kind_wird': 'Wird',
      'notif_prayer_title': 'Time for {prayer}',
      'notif_prayer_body': 'It is now time for the {prayer} prayer — {time}',
      'notif_pre_title': '{prayer} is coming up',
      'notif_pre_body': '{minutes} minutes to the {prayer} adhan ({time})',
      'notif_iqama_title': 'Iqama — {prayer}',
      'notif_iqama_body': 'The {prayer} prayer is starting now.',
      'notif_morning_azkar_title': 'Morning azkar',
      'notif_morning_azkar_body': 'Start your day with the morning azkar.',
      'notif_evening_azkar_title': 'Evening azkar',
      'notif_evening_azkar_body': 'Time for the evening azkar.',
      'notif_daily_ayah_title': 'Verse of the day',
      'notif_daily_ayah_body': 'Open the app to read today\'s verse.',
      'notif_wird_title': 'Your daily wird',
      'notif_wird_body': 'Time for your daily portion of the Quran.',
      'reader_settings': 'Reading settings',
      'reader_font': 'Font',
      'font_amiri': 'Amiri',
      'font_scheherazade': 'Scheherazade',
      'font_cairo': 'Cairo',
      'font_size': 'Font size',
      'line_spacing': 'Line spacing',
      'page_margins': 'Page margins',
      'reading_theme': 'Reading theme',
      'reading_theme_auto': 'Auto',
      'reading_theme_light': 'Light',
      'reading_theme_sepia': 'Sepia',
      'reading_theme_dark': 'Dark',
      'reading_theme_green': 'Green',
      'show_verse_numbers': 'Show verse numbers',
      'keep_screen_on': 'Keep the screen on',
      'keep_screen_on_desc': 'The screen will not dim while you read.',
      'lock_brightness': 'Lock brightness',
      'brightness': 'Brightness',
      'auto_scroll_speed': 'Auto-scroll speed',
      'auto_scroll': 'Auto-scroll',
      'stop_scroll': 'Stop scrolling',
      'reciter': 'Reciter',
      'reset_defaults': 'Reset to defaults',
      'listen': 'Listen',
      'page_word': 'Page',
      'play_from_here': 'Play from here',
      'tafsir': 'Tafsir',
      'tafsir_unavailable':
          'This tafsir is not downloaded yet. Connect once and it is saved for offline use.',
      'add_bookmark': 'Bookmark',
      'remove_bookmark': 'Remove bookmark',
      'bookmark_added': 'Verse bookmarked.',
      'bookmark_removed': 'Bookmark removed.',
      'bookmark_tag': 'Tag',
      'bookmark_tag_favorite': 'Favorite',
      'bookmark_tag_memorize': 'Memorize',
      'bookmark_tag_reflect': 'Reflect',
      'bookmark_tag_review': 'Review',
      'bookmarks': 'Bookmarks',
      'no_bookmarks_yet':
          'No bookmarks yet. Tap a verse twice to open its actions.',
      'add_note': 'Add a note',
      'note_hint': 'Your reflection on this verse…',
      'note_saved': 'Note saved.',
      'copy': 'Copy',
      'copied': 'Copied.',
      'share_text': 'Share text',
      'share_image': 'Share image',
      'choose_card_style': 'Choose a card style',
      'card_style_emerald': 'Emerald',
      'card_style_night': 'Night',
      'card_style_parchment': 'Parchment',
      'preparing_image': 'Preparing the image…',
      'share_failed': 'Sharing failed. Please try again.',
      'all': 'All',
      'app_title': 'Islamic App',
      'home': 'Home',
      'quran': 'Quran',
      'prayer': 'Prayer',
      'azkar': 'Azkar',
      'settings': 'Settings',
      'display': 'Display',
      'dark_mode': 'Dark Mode',
      'prayer_settings': 'Prayer Settings',
      'calculation_method': 'Calculation Method',
      'notifications': 'Notifications',
      'enable_prayer_notifications': 'Enable Prayer Notifications',
      'allow_reminders': 'Allow reminders for upcoming prayers.',
      'notification_permission_denied':
          'Notification permission denied. Please enable it in settings.',
      'send_test_notification': 'Send Test Notification',
      'trigger_test_reminder': 'Trigger an immediate local test reminder.',
      'test_notification_sent': 'Test notification sent.',
      'about': 'About',
      'app_version': 'App Version',
      'about_app': 'About This App',
      'about_description':
          'A comprehensive Islamic app with prayer times, Quran, Azkar, and more.',
      'language': 'Language',
      'language_arabic': 'Arabic',
      'language_english': 'English',
      'welcome_greeting': 'Peace be upon you',
      'home_intro': 'Track your prayers, read Quran, and maintain daily Azkar.',
      'prayer_times': 'Prayer Times',
      'check_prayer_schedule': 'Check today\'s prayer schedule and Qibla.',
      'browse_surahs': 'Browse surahs and read verses.',
      'morning_evening_azkar':
          'Morning and evening Azkar with tasbeeh counter.',
      'theme_method_notifications':
          'Theme, method, language, and notifications.',
      'try_again': 'Try Again',
      'retry': 'Retry',
      'unable_load_prayer_times': 'Unable to load prayer times.',
      'location_services_disabled':
          'Location services are disabled. Please enable GPS.',
      'location_permission_required':
          'Location permission is required to fetch prayer times and Qibla.',
      'daily_prayers': 'Daily Prayers',
      'location': 'Location',
      'coordinates': 'Coordinates',
      'hijri': 'Hijri',
      'gregorian': 'Gregorian',
      'next': 'Next',
      'in': 'in',
      'next_prayer': 'Next Prayer',
      'am_short': 'AM',
      'pm_short': 'PM',
      'qibla_compass': 'Qibla Compass',
      'qibla_direction': 'Qibla direction',
      'qibla_precision_desc': 'Set your prayer direction accurately.',
      'qibla_correct_direction': 'You are facing the right Qibla direction',
      'rotate_to_qibla': 'Rotate your phone toward Qibla',
      'prayer_list': 'Prayer List',
      'prayer_times_today': 'Today\'s Prayer Times',
      'today_hijri_sample': 'Friday, 15 Ramadan',
      'current_location_cairo': 'Current location: Cairo, Egypt',
      'prayer_times_auto_update':
          'Prayer times are automatically updated based on your location.',
      'change': 'Change',
      'unable_load_prayer_times_connection':
          'Unable to load prayer times. Please check your internet connection.',
      'compass_not_available': 'Compass is not available on this device.',
      'device_heading': 'Device heading',
      'search_surah_hint': 'Search surah by Arabic or English name',
      'unable_load_surahs': 'Unable to load Surahs.',
      'no_surah_match': 'No surah matched your search.',
      'verses': 'verses',
      'text_size': 'Text size',
      'unable_load_verses': 'Unable to load verses.',
      'no_verses': 'No verses available.',
      'azkar_tasbeeh': 'Azkar & Tasbeeh',
      'failed_load_azkar': 'Failed to load azkar data.',
      'no_azkar_found': 'No azkar data found.',
      'tasbeeh_counter': 'Tasbeeh Counter',
      'count': 'Count',
      'reset': 'Reset',
      'no_fixed_target': 'No fixed target count',
      'onboarding_welcome_title': 'Welcome to Islamic App',
      'onboarding_welcome_body':
          'Your companion for daily Islamic practices, prayer times, and the Holy Quran.',
      'onboarding_location_title': 'Enable Location',
      'onboarding_location_body':
          'We need your location to provide accurate prayer times for your area.',
      'onboarding_notifications_title': 'Enable Notifications',
      'onboarding_notifications_body':
          'Get reminders for prayer times and important Islamic events.',
      'back': 'Back',
      'next_btn': 'Next',
      'enable_location': 'Enable Location',
      'enable_notifications': 'Enable Notifications',
      'skip': 'Skip',
      'prayer_reminder_title': 'Prayer Reminder',
      'prayer_reminder_body': 'It is now time for prayer',
      'islamic_app_version': 'Islamic App v1.0.0',
      'search_surah': 'Search for a Surah...',
      'continue_reading': 'Continue Reading',
      'monthly_khatmah': 'Monthly Khatmah',
      'surahs_index': 'Surahs Index',
      'surahs_results': 'Surahs Results',
      'ayahs_search_results': 'Ayahs Search Results',
      'no_ayahs_match': 'No Ayahs match the search',
      'view_all': 'View All',
      'ayah_of_the_day': 'Ayah of the Day',
      'random_ayah': 'Random verse',
      'ayah_day_reference': 'Surah At-Talaq - Verses 2-3',
      'error_loading_ayah': 'Sorry, error loading Ayah',
      'sunrise': 'Sunrise',
      'fajr': 'Fajr',
      'dhuhr': 'Dhuhr',
      'asr': 'Asr',
      'maghrib': 'Maghrib',
      'isha': 'Isha',
      'user_name': 'Ahined Abdullah',
      'user_location': 'Cairo, Egypt',
      'adhan_notifications': 'Adhan Notifications',
      'customize_all': 'Customize All',
      'calc_method_desc':
          'Determine Fajr and Isha angle based on geographical location.',
      'egyptian_general_authority': 'Egyptian General Authority of Survey',
      'appearance': 'Appearance',
      'light_mode': 'Light Mode',
      'dark_mode_on': 'Dark Mode',
      'contact_us': 'Contact Us',
      'contact_us_desc':
          'We are always happy to receive your suggestions to improve the Al-Fajr app experience.',
      'send_message': 'Send Message',
      'logout': 'Log Out',
      'prayer_label_prefix': 'Prayer',
      'current_prayer': 'Current',
      'unable_load_surahs_now':
          'Unable to load surahs right now. Please check your internet connection.',
      'server_connection_error':
          'An error occurred while connecting to the server.',
      'surah_type_meccan': 'Meccan',
      'surah_type_medinan': 'Medinan',
      'search_surah_or_number_hint': 'Search surah or number...',
      'search_juz_hint': 'Search Juz...',
      'last_read': 'Last Read',
      'surah_word': 'Surah',
      'reached_verse': 'Reached verse',
      'completed_percent': 'Completed',
      'goal': 'Goal',
      'read_count_this_month': 'You read',
      'from_total_surahs': 'of total surahs',
      'surahs_tab': 'Surahs',
      'juz_tab': 'Juz',
      'juz_index': 'Juz Index',
      'juz_word': 'Juz',
      'no_juz_match': 'No Juz found',
      'tap_to_read_full_juz': 'Tap to read the full Juz',
      'result_word': 'results',
      'ayah_word': 'Ayah',
      'unable_load_verses_later':
          'Failed to load surah verses. Please try again later.',
      'bookmark_saved_at_verse': 'Bookmark saved at verse',
      'hizb_label': 'Hizb',
      'quarter_hizb_label': 'Quarter Hizb',
      'half_hizb_label': 'Half Hizb',
      'three_quarters_hizb_label': 'Three-Quarter Hizb',
      'quran_title_full': 'The Holy Quran',
      'tap_ayah_to_bookmark': 'Tap any ayah to save a bookmark',
      'juz_info_unavailable': 'Juz information is currently unavailable',
      'previous_surah': 'Previous Surah',
      'next_surah': 'Next Surah',
      'previous_juz': 'Previous Juz',
      'next_juz': 'Next Juz',
      'reader_previous': 'Previous',
      'reader_next': 'Next',
      'surah_info': 'Surah Information',
      'name_label': 'Name',
      'type_label': 'Type',
      'surah_number_label': 'Surah Number',
      'ayah_count_label': 'Ayah Count',
      'no_azkar_in_section': 'No azkar are available in this section right now',
      'muslim_azkar': 'Muslim Azkar',
      'morning_azkar': 'Morning Azkar',
      'after_prayer_azkar': 'After Prayer',
      'evening_azkar': 'Evening Azkar',
      'sleep_azkar': 'Sleep Azkar',
      'morning_azkar_subtitle': 'Starts from Fajr',
      'after_prayer_azkar_subtitle': 'After every prayer',
      'evening_azkar_subtitle': 'After Asr prayer',
      'sleep_azkar_subtitle': 'Before sleeping',
      'zekr_count_unit': 'Azkar',
      'azkar_ayah_of_day_text':
          'Indeed, in the remembrance of Allah do hearts find rest',
      'tasbeeh_phrase_subhanallah': 'Subhan Allah',
      'tasbeeh_phrase_alhamdulillah': 'Alhamdulillah',
      'tasbeeh_phrase_la_ilaha_illa_allah': 'La ilaha illa Allah',
      'tasbeeh_phrase_allahu_akbar': 'Allahu Akbar',
      'tasbeeh_phrase_astaghfirullah': 'Astaghfirullah',
      'tasbeeh_phrase_hawqala': 'La hawla wa la quwwata illa billah',
      'smart_tasbeeh': 'Smart Tasbeeh',
      'reset_all': 'Reset All',
      'repeat_label': 'Repeat',
      'azkar_categories': 'Azkar Categories',
      'search_zekr_hint': 'Search azkar...',
      'no_matching_results': 'No matching results',
      'continue_azkar': 'Continue last azkar',
      'azkar_session_complete': 'Completed — tap to repeat',
      'edit_profile': 'Edit profile',
      'profile_name_label': 'Name',
      'profile_location_label': 'City',
      'profile_invalid': 'Enter a valid name and city.',
      'profile_saved': 'Profile saved',
      'notifications_permission_denied': 'Notification permission was denied.',
      'notifications_enabled_body': 'Prayer reminders are now enabled.',
      'notifications_disabled': 'Prayer reminders are off.',
      'customize_prayer_alerts': 'Customize prayer alerts',
      'contact_message_hint': 'Write your suggestion or issue...',
      'contact_message_invalid':
          'Please write a message of at least 8 characters.',
      'contact_email_subject': 'Al-Fajr app feedback',
      'contact_launch_failed': 'Could not open the mail app.',
      'logout_confirm': 'Clear your saved profile name and location?',
      'logged_out': 'Signed out of the profile',
      'cancel': 'Cancel',
      'save': 'Save',
    },
    'ar': {
      // Imsakiya poster: weekday names and captions.
      'weekday': 'اليوم',
      'weekday_sunday': 'الأحد',
      'weekday_monday': 'الاثنين',
      'weekday_tuesday': 'الثلاثاء',
      'weekday_wednesday': 'الأربعاء',
      'weekday_thursday': 'الخميس',
      'weekday_friday': 'الجمعة',
      'weekday_saturday': 'السبت',
      'ramadan_month': 'رمضان',
      'imsakiya_footer': 'محسوبة على جهازك حسب موقعك — تطبيق الفجر.',
      // Seasonal theme, qibla compass, location picking.
      'last_read_position': 'الآية {verse} من {total} · صفحة {page}',
      'season_ramadan_greeting': 'رمضان كريم',
      'season_ramadan_subtitle':
          'شهر القرآن — وردك ومواقيتك وقيامك في مكان واحد.',
      'season_last_ten_greeting': 'العشر الأواخر',
      'season_last_ten_subtitle':
          'ليلة القدر تُلتمس في الأوتار — فاجتهد في العشر كلها.',
      'season_eid_fitr_greeting': 'عيد فطر مبارك',
      'season_eid_fitr_subtitle': 'تقبّل الله منا ومنكم صالح الأعمال.',
      'season_eid_adha_greeting': 'عيد أضحى مبارك',
      'season_eid_adha_subtitle': 'أيام التشريق: ذكرٌ وتكبيرٌ وشكر.',
      'qibla_no_sensor': 'لا توجد بوصلة في هذا الجهاز.',
      'qibla_calibrate': 'دقة البوصلة منخفضة — حرّك الهاتف على شكل رقم ٨.',
      'location_settings': 'الموقع',
      'location_settings_desc':
          'اتبع موقع الجهاز، أو ثبّت مدينة واحتفظ بمواقيتها.',
      'location_automatic': 'استخدم موقعي الحالي',
      'location_automatic_desc': 'العودة إلى تتبّع موقع الجهاز.',
      'location_search': 'ابحث عن مدينة',
      'location_search_hint': 'القاهرة، الرياض، إسطنبول…',
      'location_no_results': 'لم يُعثر على مكان بهذا الاسم.',
      'location_unknown': 'لم يُحدَّد الموقع بعد',
      'location_resolving': 'جارٍ تحديد موقعك…',
      'location_pinned': 'موقع مثبّت يدوياً — المواقيت تتبعه.',
      // Phase 4: page mode, memorisation, backup, Ramadan, downloads.
      'reader_view_mode': 'طريقة العرض',
      'view_continuous': 'متصل',
      'view_pages': 'صفحات',
      'hifz': 'الحفظ',
      'hifz_add': 'أضف مقطعاً',
      'hifz_add_verse': 'أضف للحفظ',
      'hifz_added': 'أُضيفت إلى قائمة الحفظ.',
      'hifz_empty':
          'لا يوجد شيء بعد. أضف مقطعاً وسيعود إليك للمراجعة بفواصل تتّسع كلما ثبت حفظك.',
      'hifz_all': 'كل ما تحفظه',
      'hifz_due_today': 'مراجعة اليوم',
      'hifz_due_desc': 'استرجع كل مقطع ثم قيّم نفسك بصدق.',
      'hifz_nothing_due': 'لا مراجعة اليوم، عد غداً.',
      'hifz_start_review': 'ابدأ المراجعة',
      'hifz_due_now': 'حان وقت مراجعتها',
      'hifz_next_review': 'المراجعة القادمة',
      'tasbeeh_mode_rounds': 'جولات ٣٣',
      'tasbeeh_mode_endless': 'التسبيح المطلق',
      'tasbeeh_lifetime': 'إجمالي تسبيحك',
      'tasbeeh_today': 'اليوم',
      'tasbeeh_endless_reset_title': 'تصفير العدّاد المطلق؟',
      'tasbeeh_endless_reset_body':
          'العدّاد المطلق محفوظ لك دائماً ولا يُصفَّر من تلقاء نفسه. التصفير لا رجعة فيه.',
      'preview_unavailable':
          'هذا الصوت مملوك للنظام ولا يمكن تشغيله هنا — لكنه سيُؤذَّن به في وقته.',
      'recite_voice_pack': 'حزمة التعرّف',
      'recite_voice_pack_desc':
          'أي حزمة مثبَّتة تستمع لتلاوتك. أي حزمة عربية تعمل — اختر التي تسمعك أفضل.',
      'recite_pack_automatic': 'تلقائي',
      'recite_pack_automatic_desc': 'استخدم أفضل حزمة عربية على هذا الجهاز',
      'recite_no_arabic_pack':
          'لا توجد حزمة تعرّف عربية على الجهاز بعد. بقية التطبيق تعمل بدونها — نزّل حزمة فقط إن أردت التسميع.',
      'recite_download_pack': 'تنزيل حزمة',
      'recite_download_hint':
          'يفتح إعدادات جهازك. ابحث عن التعرّف على الكلام دون إنترنت أو الإدخال الصوتي ثم أضف العربية — يمكنك تثبيت أكثر من حزمة والتبديل بينها من هنا.',
      'recite_settings_unavailable':
          'لا توجد شاشة لتنزيل حزم الصوت على هذا الجهاز.',
      'recite_show_other_packs': 'إظهار اللغات الأخرى',
      'recite_hide_other_packs': 'إخفاء اللغات الأخرى',
      'done': 'تم',
      'stt_offline_engines': 'محركات تعمل دون إنترنت',
      'stt_offline_engines_desc':
          'تعرّف يعمل على هاتفك بلا جوجل وبلا شبكة. اختياري — نزّل واحداً إن أردت، واحذفه متى شئت.',
      'stt_model_tiny': 'Whisper Tiny — متعدد اللغات',
      'stt_model_base': 'Whisper Base — متعدد اللغات',
      'stt_model_small': 'Whisper Small — متعدد اللغات',
      'stt_download_confirm':
          'التنزيل {download}، ويشغل نحو {installed} على جهازك بعد فكّ الضغط. يعمل بعدها دون إنترنت تماماً، ويمكنك حذفه في أي وقت.',
      'stt_download_failed': 'لم يكتمل التنزيل، ولم يُحفظ شيء.',
      'stt_extracting': 'جارٍ فكّ الضغط…',
      'downloading': 'جارٍ التنزيل',
      'delete': 'حذف',
      'recite_mode_check': 'سمِّع محفوظك',
      'recite_mode_identify': 'أي آية هذه؟',
      'recite_identify_hint':
          'اتلُ ما شئت وسيجدها التطبيق في المصحف — دون إنترنت، من النص المرفق.',
      'recite_identify_none': 'لا يطابق شيئاً في المصحف. جرّب كلمات أكثر.',
      'category_word': 'قسماً',
      'zekr_word': 'ذكراً',
      'greeting_morning': 'صباح الخير',
      'greeting_afternoon': 'السلام عليكم',
      'greeting_evening': 'مساء الخير',
      'ayah_of_day': 'آية اليوم',
      'mark_prayed': 'تحديد كمُؤدّاة',
      'minute_short': 'د',
      'kilometre_short': 'كم',
      'qibla_bearing': 'الاتجاه',
      'qibla_distance': 'إلى الكعبة',
      'qibla_angle_caption': 'انحراف عن القبلة',
      'qibla_turn_left': 'أدر الهاتف {degrees}° لليسار',
      'qibla_turn_right': 'أدر الهاتف {degrees}° لليمين',
      'design_gallery': 'معرض المكوّنات',
      'design_gallery_desc':
          'كل قطع نظام التصميم في شاشة واحدة. بدّل المزاج والموسم من هنا لتكتشف أي تنافر في ثوانٍ بدل يوم الإطلاق.',
      'design_gallery_glass':
          'الزجاج يحتاج محتوى يمرّ تحته، وإلا فهو مستطيل رمادي.',
      'seasonal_preview': 'معاينة المواسم',
      'seasonal_preview_desc':
          'جرّب أي موسم في أي يوم لترى ألوانه ولافتته ومقدمته قبل أن يأتي. يبقى التطبيق بزيّ الموسم حتى تعود للوضع التلقائي.',
      'seasonal_preview_auto': 'تلقائي (حسب التاريخ الهجري)',
      'seasonal_preview_auto_none': 'لا موسم اليوم — التطبيق بألوانه المعتادة.',
      'seasonal_preview_has_intro': 'له مقدمة مصوّرة',
      'seasonal_preview_no_intro': 'لا توجد مقدمة بعد',
      'seasonal_preview_play': 'شغّل المقدمة',
      'seasonal_preview_live': 'معاينة حيّة',
      'seasonal_preview_active': 'وضع معاينة المواسم مفعَّل',
      'seasonal_preview_exit': 'عودة للتلقائي',
      'recite_title': 'التسميع',
      'recite_start': 'ابدأ التسميع',
      'recite_stop': 'إيقاف',
      'recite_experimental':
          'تجريبي: محرّك التعرّف في الجهاز غير مُعدّ للتلاوة، فاعتبر النتيجة عوناً على المراجعة لا حكماً.',
      'recite_progress': 'وصلت إلى',
      'recite_heard': 'ما تم سماعه',
      'recite_legend_ok': 'صحيح',
      'recite_legend_near': 'قريب',
      'recite_legend_wrong': 'راجعها',
      'recite_no_permission': 'نحتاج إذن الميكروفون لمتابعة تسميعك.',
      'recite_no_arabic':
          'لا توجد حزمة تعرّف عربية على الجهاز، ثبّتها من إعدادات النظام.',
      'recite_unavailable': 'خدمة التعرّف على الكلام غير متاحة على هذا الجهاز.',
      'recite_failed': 'تعذّر بدء الاستماع، حاول مرة أخرى.',
      'intro_skip': 'تخطٍّ',
      'seasonal_intro': 'مقدمة المناسبة',
      'seasonal_intro_desc':
          'تشغيل مقدمة قصيرة لرمضان أو العيد مرة واحدة يومياً عند فتح التطبيق.',
      'hifz_review': 'مراجعة',
      'hifz_mask_hidden': 'مخفي',
      'hifz_mask_letters': 'أول الحروف',
      'hifz_mask_none': 'ظاهر',
      'hifz_tap_word': 'اضغط أي كلمة لكشفها.',
      'hifz_how_was_it': 'كيف كان استرجاعك؟',
      'hifz_grade_again': 'أعد',
      'hifz_grade_good': 'جيد',
      'hifz_grade_easy': 'سهل',
      'hifz_quiz': 'أكمل الآية',
      'quiz_prompt': 'ما الآية التي تليها؟',
      'quiz_score': 'النتيجة',
      'quiz_next': 'التالي',
      'quiz_restart': 'جولة جديدة',
      'backup': 'النسخ الاحتياطي',
      'backup_desc': 'صدّر كل شيء في ملف، أو استعده.',
      'backup_explain':
          'المرجعيات والملاحظات وسجل القراءة والحفظ وكل الإعدادات — في ملف واحد تحتفظ به.',
      'backup_export': 'تصدير نسخة',
      'backup_export_desc': 'شاركه إلى درايف أو البريد أو أي مكان.',
      'backup_import': 'استعادة من ملف',
      'backup_import_desc': 'العناصر المتطابقة تُستبدل.',
      'backup_restored': 'تمت الاستعادة.',
      'backup_invalid': 'هذا الملف ليس نسخة احتياطية من التطبيق.',
      'backup_newer_version': 'هذه النسخة أُنشئت بإصدار أحدث من التطبيق.',
      'ramadan_day': 'رمضان {day}',
      'ramadan_until_iftar': 'حتى الإفطار',
      'ramadan_until_imsak': 'حتى الإمساك',
      'tarawih_tonight': 'تراويح الليلة',
      'tarawih_mark': 'سجّلها',
      'tarawih_done': 'تمت',
      'reciter_library': 'القرّاء والتنزيلات',
      'download': 'تنزيل',
      'downloaded_offline': 'متاحة دون إنترنت',
      'downloads_size': 'المساحة المستخدمة',
      'downloads_clear': 'حذف الكل',
      'downloads_delete': 'حذف',
      // Imsakiya, the last ten nights, azkar cards.
      'zekr_done': 'تم',
      'zekr_tap_to_count': 'اضغط للعد · المتبقي',
      'imsakiya': 'إمساكية رمضان',
      'imsakiya_desc':
          'الإمساك والفجر والإفطار لكل أيام الشهر، محسوبة من موقعك.',
      'imsakiya_note':
          'الإمساك مطبوع قبل الفجر بعشر دقائق كما جرت العادة في الإمساكيات.',
      'imsakiya_day': 'اليوم',
      'imsakiya_unavailable': 'الإمساكية تحتاج تحديد موقعك.',
      'imsak': 'الإمساك',
      'iftar': 'الإفطار',
      'event_laylat_qadr_expected': 'يُرجى أن تكون ليلة القدر',
      'event_last_ten': 'من العشر الأواخر',
      'event_odd_night': 'ليلة وترية من العشر الأواخر',
      'laylat_qadr_note':
          'ليلة القدر تُلتمس في أوتار العشر الأواخر، والسابع والعشرون أرجاها في الروايات لا يقيناً — فاجتهد في العشر كلها.',
      // Phase 3: adhan sounds, khatmah, daily wird, stats, occasions.
      'adhan_sound_rifat': 'أذان القاهرة — محمد رفعت',
      'adhan_sound_mustafa_ismail': 'أذان — مصطفى إسماعيل',
      'adhan_sound_fajr_abu_rahiq': 'أذان الفجر — إبراهيم جبر أبو رحيق',
      'adhan_sound_custom': 'أذانك',
      'adhan_sound_custom_desc': 'ملف أضفته بنفسك',
      'adhan_sound_saved': 'تم حفظ الأذان.',
      'import_adhan': 'أضف ملف أذان',
      'pick_device_sound': 'اختر من أصوات الجهاز',
      'preview_sound': 'استمع له',
      'adhan_import_unsupported':
          'إضافة ملف تحتاج أندرويد ١٠ أو أحدث. يمكنك اختيار صوت موجود على الجهاز.',
      'adhan_import_failed': 'تعذّرت إضافة الملف، جرّب ملفاً آخر.',
      'fajr_adhan_sound': 'أذان مختلف للفجر',
      'fajr_adhan_sound_desc':
          'أذان الفجر يزيد فيه «الصلاة خير من النوم»، ولذلك يفضّل كثيرون تسجيلاً خاصاً به.',
      'narrated_by': 'التخريج',
      'khatmah_plan': 'خطة الختمة',
      'khatmah_plan_desc': 'اختر مدة ختمك للمصحف، ويُحسب لك ورد كل يوم.',
      'khatmah_in_days': 'في {days} يوماً',
      'khatmah_custom': 'مدة مخصصة',
      'khatmah_days_label': 'عدد الأيام',
      'khatmah_progress': '{read} من {total} صفحة',
      'khatmah_ahead': 'أنت متقدّم بـ {pages} صفحة.',
      'khatmah_behind': 'أنت متأخر بـ {pages} صفحة، وورد اليوم يغطيها.',
      'khatmah_cancel': 'إنهاء الخطة',
      'khatmah_completed': 'أتممت المصحف، تقبّل الله منك.',
      'khatmah_start_new': 'ابدأ ختمة جديدة',
      'khatmah_day_of': 'اليوم {day} من {days}',
      'today_portion': 'ورد اليوم',
      'today_read': 'قرأت اليوم',
      'days_left': 'الأيام المتبقية',
      'pages_count': '{count} صفحة',
      'reading_stats': 'إحصاءات القراءة',
      'reading_streak': 'سلسلة الأيام',
      'reading_streak_desc': 'أيام متتالية قرأت فيها صفحة على الأقل.',
      'current_streak': 'الحالية',
      'longest_streak': 'الأطول',
      'today_read_pages': 'اليوم: {count} صفحة',
      'reading_totals': 'الإجمالي',
      'days_read': 'أيام',
      'pages_read': 'صفحات',
      'time_read': 'الوقت',
      'this_week': 'هذا الأسبوع',
      'reading_year': 'خريطة السنة',
      'reading_year_desc': 'مربّع لكل يوم، وكلما زاد اللون زادت قراءتك.',
      'daily_wird': 'الورد اليومي',
      'wird_quran': 'ورد القرآن',
      'wird_morning_azkar': 'أذكار الصباح',
      'wird_evening_azkar': 'أذكار المساء',
      'wird_tasbeeh': 'التسبيح',
      'wird_done_of': '{done} من {total}',
      'wird_unavailable': 'تعذّر عرض الورد الآن.',
      'occasion_reminders': 'المناسبات والصيام',
      'occasion_reminders_desc':
          'الجمعة، وأيام الصيام المستحبة، والمناسبات الهجرية.',
      'friday_reminder': 'تذكير الجمعة',
      'friday_reminder_desc': 'سورة الكهف بعد الفجر بساعة.',
      'fasting_reminder': 'تذكير الصيام',
      'fasting_reminder_desc': 'ليلة الاثنين والخميس والأيام البيض.',
      'islamic_events': 'المناسبات الهجرية',
      'islamic_events_desc': 'عاشوراء وعرفة والعيدان ورمضان والأيام البيض.',
      'notif_kind_event': 'مناسبة',
      'notif_friday_title': 'يوم الجمعة',
      'notif_friday_body': 'اقرأ سورة الكهف وأكثر من الصلاة على النبي ﷺ.',
      'notif_event_body': 'افتح التقويم لتعرف مناسبة اليوم.',
      'notif_event_fasting_body': 'يوم يُستحب صيامه.',
      'notif_fasting_title': 'صيام غداً؟',
      'notif_fasting_body': 'غداً الاثنين أو الخميس، ومن السنة صيامه.',
      'notif_fasting_white_body': 'غداً من الأيام البيض.',
      'widget_in_hours': 'بعد {hours} س {minutes} د',
      'widget_in_minutes': 'بعد {minutes} دقيقة',
      // Index modes, notes, player, prayer tuning, Hijri calendar, adhan sounds.
      'hizb_tab': 'الأحزاب',
      'pages_tab': 'الصفحات',
      'sajdah_tab': 'السجدات',
      'hizb_index': 'فهرس الأحزاب',
      'pages_index': 'فهرس الصفحات',
      'sajdah_index': 'آيات السجدة',
      'sajdah_word': 'سجدة',
      'starts_at': 'يبدأ من',
      'search_hizb_hint': 'ابحث برقم الحزب…',
      'search_page_hint': 'ابحث برقم الصفحة…',
      'jump_to': 'انتقل إلى',
      'invalid_reference': 'هذا الموضع غير موجود.',
      'open': 'افتح',
      'no_results': 'لا توجد نتائج.',
      'my_reflections': 'تدبّراتي',
      'no_notes_yet':
          'لا توجد ملاحظات بعد. افتح آية واختر «إضافة ملاحظة» لتظهر هنا.',
      'search_notes_hint': 'ابحث في ملاحظاتك…',
      'export_notes': 'تصدير',
      'sort': 'ترتيب',
      'sort_newest': 'الأحدث أولاً',
      'sort_mushaf': 'ترتيب المصحف',
      'open_in_reader': 'افتح في المصحف',
      'player': 'المشغّل',
      'play': 'تشغيل',
      'pause': 'إيقاف مؤقت',
      'stop': 'إيقاف',
      'playback_speed': 'سرعة التلاوة',
      'repeat_verse': 'تكرار الآية',
      'repeat_verse_desc': 'يكرر الآية التي تُتلى الآن.',
      'repeat_range': 'تكرار مقطع',
      'repeat_range_desc': 'اختر أول آية وآخر آية وعدد مرات التكرار.',
      'range_from': 'من آية',
      'range_to': 'إلى آية',
      'repeat_times': 'عدد التكرارات',
      'repeat_endless': 'بلا حد',
      'start_repeat': 'ابدأ التكرار',
      'sleep_timer': 'مؤقت النوم',
      'end_of_passage': 'نهاية المقطع',
      'minutes_short': 'دقيقة',
      'prayer_calculation_settings': 'ضبط المواقيت',
      'today_preview': 'مواقيت اليوم',
      'asr_madhab': 'حساب العصر',
      'asr_madhab_desc': 'الحنفي يعتمد ظلّاً أطول، فيتأخر العصر.',
      'madhab_shafi': 'الشافعي والمالكي والحنبلي',
      'madhab_hanafi': 'الحنفي',
      'high_latitude_rule': 'قاعدة خطوط العرض العالية',
      'high_latitude_desc':
          'تُستخدم حيث لا تغيب الشمس بما يكفي لحساب الفجر والعشاء.',
      'high_lat_middle_of_the_night': 'منتصف الليل',
      'high_lat_seventh_of_the_night': 'سُبع الليل',
      'high_lat_twilight_angle': 'زاوية الشفق',
      'manual_offsets': 'تعديل يدوي بالدقائق',
      'manual_offsets_desc': 'قدّم أو أخّر أي صلاة بدقائق لتطابق مسجد الحي.',
      'reset_offsets': 'مسح التعديلات',
      'hijri_adjustment': 'تعديل التاريخ الهجري',
      'hijri_adjustment_desc':
          'حرّك التاريخ الهجري يوماً إذا اختلفت الرؤية في بلدك.',
      'hijri_calendar': 'التقويم الهجري',
      'hijri_calendar_desc':
          'الشهر الهجري بمناسباته وأيام صيامه ومواقيت صلاته.',
      'day_sun': 'أحد',
      'day_mon': 'إثنين',
      'day_tue': 'ثلاثاء',
      'day_wed': 'أربعاء',
      'day_thu': 'خميس',
      'day_fri': 'جمعة',
      'day_sat': 'سبت',
      'event_islamic_new_year': 'رأس السنة الهجرية',
      'event_ashura': 'عاشوراء',
      'event_mawlid': 'المولد النبوي',
      'event_isra_miraj': 'الإسراء والمعراج',
      'event_mid_shaban': 'النصف من شعبان',
      'event_ramadan_start': 'أول رمضان',
      'event_laylat_qadr': 'ليلة القدر (٢٧)',
      'event_eid_fitr': 'عيد الفطر',
      'event_arafah': 'يوم عرفة',
      'event_eid_adha': 'عيد الأضحى',
      'event_tashreeq': 'أيام التشريق',
      'event_white_days': 'الأيام البيض',
      'event_monday_thursday': 'يوم صيام مستحب (الاثنين والخميس)',
      'adhan_sound': 'صوت الأذان',
      'adhan_sound_desc': 'يُشغَّل للصلوات المضبوطة على وضع الأذان.',
      'adhan_sound_system': 'نغمة الإشعار الافتراضية',
      'adhan_sound_makkah': 'أذان مكة',
      'adhan_sound_madinah': 'أذان المدينة',
      'adhan_sound_alafasy': 'أذان العفاسي',
      'adhan_sound_missing': 'ملف الصوت غير مضاف بعد',
      'adhan_sound_hint':
          'لتفعيل أذان، أضف ملفه الصوتي إلى android/app/src/main/res/raw/ ثم أضف معرّفه في NotificationService.bundledAdhanSoundIds.',
      // Phase 1 & 2: notification centre, reader controls, bookmarks, tafsir.
      'notification_center': 'مركز التنبيهات',
      'notification_center_desc':
          'كل التنبيهات في مكان واحد، مع معاينة لما سيصلك فعلاً.',
      'notif_master': 'تفعيل التنبيهات',
      'notif_master_desc': 'يجدول تنبيهات الأسبوع القادم على هذا الجهاز.',
      'notif_scheduled_count': 'عدد التنبيهات المجدولة: {count}',
      'notif_none_scheduled': 'لا توجد تنبيهات مجدولة بعد.',
      'notif_reschedule': 'إعادة الجدولة',
      'notif_exact_alarms_missing':
          'التنبيه الدقيق غير مفعّل، لذلك قد تتأخر التنبيهات بضع دقائق.',
      'notif_allow_exact_alarms': 'السماح بالتنبيه الدقيق',
      'send_test': 'إرسال تجريبي',
      'prayer_alerts': 'تنبيهات الصلاة',
      'prayer_alerts_desc': 'اختر طريقة التنبيه لكل صلاة على حدة.',
      'apply_to_all': 'كل الصلوات',
      'mode_off': 'إيقاف',
      'mode_silent': 'صامت',
      'mode_vibrate': 'اهتزاز',
      'mode_notification': 'نغمة',
      'mode_adhan': 'أذان',
      'pre_adhan_reminder': 'تنبيه قبل الأذان',
      'pre_adhan_desc': 'تنبيه مبكر لتستعد للصلاة قبل دخول وقتها.',
      'iqama_reminder': 'تنبيه الإقامة',
      'iqama_desc': 'يُرسل بعد الأذان بمدة الإقامة في مسجدك.',
      'minutes_off': 'بدون',
      'minutes_value': '{minutes} دقيقة',
      'azkar_reminders': 'تنبيهات الأذكار',
      'azkar_reminders_desc': 'مرتبطة بمواقيت الشمس لا بساعة ثابتة.',
      'morning_azkar_reminder': 'أذكار الصباح',
      'evening_azkar_reminder': 'أذكار المساء',
      'offset_after_fajr': 'بعد الفجر',
      'offset_after_asr': 'بعد العصر',
      'daily_reminders': 'تنبيهات يومية',
      'daily_ayah_reminder': 'آية اليوم',
      'wird_reminder': 'الورد اليومي',
      'change_time': 'تغيير الوقت',
      'quiet_hours': 'ساعات الهدوء',
      'quiet_hours_desc':
          'تُسكت التنبيهات الاختيارية فقط، ولا تؤثر على تنبيهات الصلاة.',
      'quiet_from': 'من',
      'quiet_to': 'إلى',
      'upcoming_alerts': 'التنبيهات القادمة',
      'today': 'اليوم',
      'tomorrow': 'غداً',
      'notif_kind_prayer': 'صلاة',
      'notif_kind_pre': 'قبل الأذان',
      'notif_kind_iqama': 'إقامة',
      'notif_kind_azkar': 'أذكار',
      'notif_kind_ayah': 'آية',
      'notif_kind_wird': 'ورد',
      'notif_prayer_title': 'حان وقت {prayer}',
      'notif_prayer_body': 'حان الآن وقت صلاة {prayer} — {time}',
      'notif_pre_title': 'اقترب وقت {prayer}',
      'notif_pre_body': 'بقي {minutes} دقيقة على أذان {prayer} ({time})',
      'notif_iqama_title': 'الإقامة — {prayer}',
      'notif_iqama_body': 'أقيمت صلاة {prayer} الآن.',
      'notif_morning_azkar_title': 'أذكار الصباح',
      'notif_morning_azkar_body': 'ابدأ يومك بأذكار الصباح.',
      'notif_evening_azkar_title': 'أذكار المساء',
      'notif_evening_azkar_body': 'حان وقت أذكار المساء.',
      'notif_daily_ayah_title': 'آية اليوم',
      'notif_daily_ayah_body': 'افتح التطبيق لقراءة آية اليوم.',
      'notif_wird_title': 'وردك اليومي',
      'notif_wird_body': 'حان وقت وردك اليومي من القرآن.',
      'reader_settings': 'إعدادات القراءة',
      'reader_font': 'نوع الخط',
      'font_amiri': 'أميري',
      'font_scheherazade': 'شهرزاد',
      'font_cairo': 'القاهرة',
      'font_size': 'حجم الخط',
      'line_spacing': 'تباعد الأسطر',
      'page_margins': 'هوامش الصفحة',
      'reading_theme': 'وضع القراءة',
      'reading_theme_auto': 'تلقائي',
      'reading_theme_light': 'نهاري',
      'reading_theme_sepia': 'سيبيا',
      'reading_theme_dark': 'ليلي',
      'reading_theme_green': 'أخضر',
      'show_verse_numbers': 'إظهار أرقام الآيات',
      'keep_screen_on': 'إبقاء الشاشة مضاءة',
      'keep_screen_on_desc': 'لن تنطفئ الشاشة أثناء القراءة.',
      'lock_brightness': 'قفل سطوع الشاشة',
      'brightness': 'السطوع',
      'auto_scroll_speed': 'سرعة التمرير التلقائي',
      'auto_scroll': 'تمرير تلقائي',
      'stop_scroll': 'إيقاف التمرير',
      'reciter': 'القارئ',
      'reset_defaults': 'استعادة الإعدادات الافتراضية',
      'listen': 'استماع',
      'page_word': 'صفحة',
      'play_from_here': 'استماع من هنا',
      'tafsir': 'التفسير',
      'tafsir_unavailable':
          'هذا التفسير غير محمّل بعد. اتصل بالإنترنت مرة واحدة ليُحفظ للقراءة دون إنترنت.',
      'add_bookmark': 'حفظ مرجعية',
      'remove_bookmark': 'إزالة المرجعية',
      'bookmark_added': 'تم حفظ الآية في المرجعيات.',
      'bookmark_removed': 'تم حذف المرجعية.',
      'bookmark_tag': 'التصنيف',
      'bookmark_tag_favorite': 'مفضلة',
      'bookmark_tag_memorize': 'حفظ',
      'bookmark_tag_reflect': 'تدبّر',
      'bookmark_tag_review': 'مراجعة',
      'bookmarks': 'المرجعيات',
      'no_bookmarks_yet': 'لا توجد مرجعيات بعد. اضغط الآية مرتين لفتح أدواتها.',
      'add_note': 'إضافة ملاحظة',
      'note_hint': 'خاطرتك حول هذه الآية…',
      'note_saved': 'تم حفظ الملاحظة.',
      'copy': 'نسخ',
      'copied': 'تم النسخ.',
      'share_text': 'مشاركة نص',
      'share_image': 'مشاركة صورة',
      'choose_card_style': 'اختر شكل البطاقة',
      'card_style_emerald': 'زمردي',
      'card_style_night': 'ليلي',
      'card_style_parchment': 'ورقي',
      'preparing_image': 'جارٍ تجهيز الصورة…',
      'share_failed': 'تعذّرت المشاركة، حاول مرة أخرى.',
      'all': 'الكل',
      'app_title': 'الفجر',
      'home': 'الرئيسية',
      'quran': 'القرآن',
      'prayer': 'الصلاة',
      'azkar': 'الأذكار',
      'settings': 'الإعدادات',
      'display': 'العرض',
      'dark_mode': 'الوضع الداكن',
      'prayer_settings': 'إعدادات الصلاة',
      'calculation_method': 'طريقة الحساب',
      'notifications': 'الإشعارات',
      'enable_prayer_notifications': 'تفعيل إشعارات الصلاة',
      'allow_reminders': 'السماح بتذكيرات الصلوات القادمة.',
      'notification_permission_denied':
          'تم رفض إذن الإشعارات. يرجى تفعيله من إعدادات النظام.',
      'send_test_notification': 'إرسال إشعار تجريبي',
      'trigger_test_reminder': 'إرسال تذكير تجريبي فوري.',
      'test_notification_sent': 'تم إرسال الإشعار التجريبي.',
      'about': 'حول التطبيق',
      'app_version': 'إصدار التطبيق',
      'about_app': 'عن هذا التطبيق',
      'about_description':
          'تطبيق إسلامي شامل لمواقيت الصلاة والقرآن والأذكار والمزيد.',
      'language': 'اللغة',
      'language_arabic': 'العربية',
      'language_english': 'الإنجليزية',
      'welcome_greeting': 'السلام عليكم ورحمة الله وبركاته',
      'home_intro': 'تابع صلاتك، اقرأ القرآن، واستمر في أذكارك اليومية.',
      'prayer_times': 'مواقيت الصلاة',
      'check_prayer_schedule': 'اعرض مواقيت اليوم والقبلة.',
      'browse_surahs': 'تصفح السور واقرأ الآيات.',
      'morning_evening_azkar': 'أذكار الصباح والمساء مع عداد تسبيح.',
      'theme_method_notifications': 'الثيم وطريقة الحساب واللغة والإشعارات.',
      'try_again': 'حاول مرة أخرى',
      'retry': 'إعادة المحاولة',
      'unable_load_prayer_times': 'تعذر تحميل مواقيت الصلاة.',
      'location_services_disabled': 'خدمات الموقع متوقفة. يرجى تفعيل GPS.',
      'location_permission_required':
          'نحتاج إذن الموقع لجلب مواقيت الصلاة والقبلة.',
      'daily_prayers': 'الصلوات اليومية',
      'location': 'الموقع',
      'coordinates': 'الإحداثيات',
      'hijri': 'الهجري',
      'gregorian': 'الميلادي',
      'next': 'القادمة',
      'in': 'بعد',
      'next_prayer': 'الصلاة القادمة',
      'am_short': 'ص',
      'pm_short': 'م',
      'qibla_compass': 'بوصلة القبلة',
      'qibla_direction': 'اتجاه القبلة',
      'qibla_precision_desc': 'حدد اتجاه صلاتك بدقة',
      'qibla_correct_direction': 'أنت في الاتجاه الصحيح',
      'rotate_to_qibla': 'حرّك هاتفك حتى يتجه نحو القبلة',
      'prayer_list': 'قائمة الصلوات',
      'prayer_times_today': 'مواقيت الصلاة اليوم',
      'today_hijri_sample': 'الجمعة، ١٥ رمضان',
      'current_location_cairo': 'الموقع الحالي: القاهرة، مصر',
      'prayer_times_auto_update': 'يتم تحديث المواقيت تلقائياً حسب موقعك',
      'change': 'تغيير',
      'unable_load_prayer_times_connection':
          'تعذر تحميل مواقيت الصلاة. تأكد من اتصال الإنترنت.',
      'compass_not_available': 'البوصلة غير متاحة على هذا الجهاز.',
      'device_heading': 'اتجاه الجهاز',
      'search_surah_hint': 'ابحث عن السورة بالعربية أو الإنجليزية',
      'unable_load_surahs': 'تعذر تحميل السور.',
      'no_surah_match': 'لا توجد سورة مطابقة للبحث.',
      'verses': 'آية',
      'text_size': 'حجم النص',
      'unable_load_verses': 'تعذر تحميل الآيات.',
      'no_verses': 'لا توجد آيات متاحة.',
      'azkar_tasbeeh': 'الأذكار والتسبيح',
      'failed_load_azkar': 'تعذر تحميل بيانات الأذكار.',
      'no_azkar_found': 'لا توجد بيانات أذكار.',
      'tasbeeh_counter': 'عداد التسبيح',
      'count': 'تسبيح',
      'reset': 'إعادة',
      'no_fixed_target': 'لا يوجد عدد محدد',
      'onboarding_welcome_title': 'مرحبا بك في تطبيق الفجر',
      'onboarding_welcome_body':
          'رفيقك اليومي للعبادات ومواقيت الصلاة والقرآن الكريم.',
      'onboarding_location_title': 'تفعيل الموقع',
      'onboarding_location_body':
          'نحتاج موقعك لتقديم مواقيت صلاة دقيقة لمنطقتك.',
      'onboarding_notifications_title': 'تفعيل الإشعارات',
      'onboarding_notifications_body':
          'احصل على تذكيرات بمواقيت الصلاة والمناسبات الإسلامية.',
      'back': 'السابق',
      'next_btn': 'التالي',
      'enable_location': 'تفعيل الموقع',
      'enable_notifications': 'تفعيل الإشعارات',
      'skip': 'تخطي',
      'prayer_reminder_title': 'تذكير صلاة',
      'prayer_reminder_body': 'حان الآن وقت الصلاة',
      'islamic_app_version': 'الفجر v1.0.0',
      'search_surah': 'ابحث عن سورة...',
      'continue_reading': 'استمر في التلاوة',
      'monthly_khatmah': 'الورد الشهري',
      'surahs_index': 'فهرس السور',
      'surahs_results': 'نتائج السور',
      'ayahs_search_results': 'نتائج البحث في الآيات',
      'no_ayahs_match': 'لم يتم العثور على آيات مطابقة للبحث',
      'view_all': 'عرض الكل',
      'ayah_of_the_day': 'آية اليوم',
      'random_ayah': 'آية عشوائية',
      'ayah_day_reference': 'سورة الطلاق - آية ٢-٣',
      'error_loading_ayah': 'عذراً، حدث خطأ في تحميل الآية',
      'sunrise': 'الشروق',
      'fajr': 'الفجر',
      'dhuhr': 'الظهر',
      'asr': 'العصر',
      'maghrib': 'المغرب',
      'isha': 'العشاء',
      'user_name': 'أحمد عبدالله',
      'user_location': 'القاهرة، مصر',
      'adhan_notifications': 'تنبيهات الأذان',
      'customize_all': 'تخصيص الكل',
      'calc_method_desc':
          'تحديد زاوية الفجر والعشاء بناءً على الموقع الجغرافي.',
      'egyptian_general_authority': 'الهيئة العامة المصرية للمساحة',
      'appearance': 'المظهر',
      'light_mode': 'الوضع الفاتح',
      'dark_mode_on': 'الوضع الداكن',
      'contact_us': 'تواصل معنا',
      'contact_us_desc':
          'نسعد دائماً باستقبال اقتراحاتكم لتطوير تجربة تطبيق الفجر.',
      'send_message': 'إرسال رسالة',
      'logout': 'تسجيل الخروج',
      'prayer_label_prefix': 'صلاة',
      'current_prayer': 'الحالية',
      'unable_load_surahs_now':
          'لا يمكن تحميل السور حالياً. تأكد من اتصال الإنترنت.',
      'server_connection_error': 'حدث خطأ أثناء الاتصال بالخادم.',
      'surah_type_meccan': 'مكية',
      'surah_type_medinan': 'مدنية',
      'search_surah_or_number_hint': 'ابحث عن سورة أو رقم...',
      'search_juz_hint': 'ابحث عن جزء...',
      'last_read': 'آخر قراءة',
      'surah_word': 'سورة',
      'reached_verse': 'وصلت إلى الآية',
      'completed_percent': 'تم إنجاز',
      'goal': 'الهدف',
      'read_count_this_month': 'قرأت',
      'from_total_surahs': 'من إجمالي السور',
      'surahs_tab': 'السور',
      'juz_tab': 'الأجزاء',
      'juz_index': 'فهرس الأجزاء',
      'juz_word': 'جزء',
      'no_juz_match': 'لم يتم العثور على أي جزء',
      'tap_to_read_full_juz': 'اضغط لقراءة الجزء كاملًا',
      'result_word': 'نتيجة',
      'ayah_word': 'الآية',
      'unable_load_verses_later':
          'فشل في تحميل آيات السورة. يرجى المحاولة لاحقاً.',
      'bookmark_saved_at_verse': 'تم حفظ العلامة عند الآية',
      'hizb_label': 'الحزب',
      'quarter_hizb_label': 'ربع الحزب',
      'half_hizb_label': 'نصف الحزب',
      'three_quarters_hizb_label': 'ثلاثة أرباع الحزب',
      'quran_title_full': 'القرآن الكريم',
      'tap_ayah_to_bookmark': 'اضغط على أي آية لحفظ العلامة فيها',
      'juz_info_unavailable': 'معلومات الجزء غير متاحة حالياً',
      'previous_surah': 'السورة السابقة',
      'next_surah': 'السورة التالية',
      'previous_juz': 'الجزء السابق',
      'next_juz': 'الجزء التالي',
      'reader_previous': 'السابق',
      'reader_next': 'التالي',
      'surah_info': 'معلومات السورة',
      'name_label': 'الاسم',
      'type_label': 'النوع',
      'surah_number_label': 'رقم السورة',
      'ayah_count_label': 'عدد الآيات',
      'no_azkar_in_section': 'لا توجد أذكار في هذا القسم حالياً',
      'muslim_azkar': 'أذكار المسلم',
      'morning_azkar': 'أذكار الصباح',
      'after_prayer_azkar': 'بعد الصلاة',
      'evening_azkar': 'أذكار المساء',
      'sleep_azkar': 'أذكار النوم',
      'morning_azkar_subtitle': 'تبدأ من طلوع الفجر',
      'after_prayer_azkar_subtitle': 'دبر كل صلاة',
      'evening_azkar_subtitle': 'بعد صلاة العصر',
      'sleep_azkar_subtitle': 'قبل النوم',
      'zekr_count_unit': 'ذكراً',
      'azkar_ayah_of_day_text': 'أَلا بِذِكْرِ اللَّهِ تَطْمَئِنُّ الْقُلُوبُ',
      'tasbeeh_phrase_subhanallah': 'سبحان الله',
      'tasbeeh_phrase_alhamdulillah': 'الحمد لله',
      'tasbeeh_phrase_la_ilaha_illa_allah': 'لا إله إلا الله',
      'tasbeeh_phrase_allahu_akbar': 'الله أكبر',
      'tasbeeh_phrase_astaghfirullah': 'استغفر الله',
      'tasbeeh_phrase_hawqala': 'لا حول ولا قوة إلا بالله',
      'smart_tasbeeh': 'المسبحة الذكية',
      'reset_all': 'إعادة تعيين الكل',
      'repeat_label': 'التكرار',
      'azkar_categories': 'تصنيفات الأذكار',
      'search_zekr_hint': 'ابحث عن ذكر...',
      'no_matching_results': 'لا توجد نتائج مطابقة للبحث',
      'continue_azkar': 'متابعة آخر ذكر',
      'azkar_session_complete': 'اكتملت — اضغط للإعادة',
      'edit_profile': 'تعديل الملف الشخصي',
      'profile_name_label': 'الاسم',
      'profile_location_label': 'المدينة',
      'profile_invalid': 'أدخل اسماً ومدينة صالحين.',
      'profile_saved': 'تم حفظ الملف الشخصي',
      'notifications_permission_denied': 'تم رفض إذن الإشعارات.',
      'notifications_enabled_body': 'تم تفعيل تذكيرات الصلاة.',
      'notifications_disabled': 'تم إيقاف تذكيرات الصلاة.',
      'customize_prayer_alerts': 'تخصيص تنبيهات الصلوات',
      'contact_message_hint': 'اكتب اقتراحك أو المشكلة...',
      'contact_message_invalid': 'اكتب رسالة من 8 أحرف على الأقل.',
      'contact_email_subject': 'ملاحظات تطبيق الفجر',
      'contact_launch_failed': 'تعذر فتح تطبيق البريد.',
      'logout_confirm': 'مسح الاسم والمدينة المحفوظين؟',
      'logged_out': 'تم تسجيل الخروج من الملف الشخصي',
      'cancel': 'إلغاء',
      'save': 'حفظ',
    },
  };

  static String tr(BuildContext context, String key) {
    final languageCode = Localizations.localeOf(context).languageCode;
    final values =
        _localizedValues[languageCode] ?? _localizedValues[_fallbackLanguage]!;
    return values[key] ?? _localizedValues[_fallbackLanguage]![key] ?? key;
  }

  static bool isRtl(BuildContext context) {
    return Localizations.localeOf(context).languageCode == 'ar';
  }

  /// Translate without a [BuildContext].
  ///
  /// Used by background work such as the notification scheduler, which builds
  /// user-facing text long before any widget tree exists.
  ///
  /// [replacements] substitutes `{placeholder}` tokens inside the string.
  static String translate(
    String languageCode,
    String key, {
    Map<String, String> replacements = const {},
  }) {
    final values =
        _localizedValues[languageCode] ?? _localizedValues[_fallbackLanguage]!;
    var result =
        values[key] ?? _localizedValues[_fallbackLanguage]![key] ?? key;

    for (final entry in replacements.entries) {
      result = result.replaceAll('{${entry.key}}', entry.value);
    }
    return result;
  }
}

extension AppLocalizationContext on BuildContext {
  String tr(String key) => AppLocalizations.tr(this, key);

  bool get isAppRtl => AppLocalizations.isRtl(this);

  TextDirection get appTextDirection =>
      isAppRtl ? TextDirection.rtl : TextDirection.ltr;
}
