import 'package:flutter/material.dart';

/// Lightweight in-app localization for Arabic and English.
class AppLocalizations {
  AppLocalizations._();

  static const String _fallbackLanguage = 'en';

  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'app_title': 'Islamic App',
      'home': 'Home',
      'quran': 'Quran',
      'prayer': 'Prayer',
      'azkar': 'Azkar',
      'settings': 'Settings',
      'display': 'Display',
      'dark_mode': 'Dark Mode',
      'prayer_settings': 'Prayer Settings',
      'calculation_method': 'Calculation Method',
      'notifications': 'Notifications',
      'enable_prayer_notifications': 'Enable Prayer Notifications',
      'allow_reminders': 'Allow reminders for upcoming prayers.',
      'notification_permission_denied':
          'Notification permission denied. Please enable it in settings.',
      'send_test_notification': 'Send Test Notification',
      'trigger_test_reminder': 'Trigger an immediate local test reminder.',
      'test_notification_sent': 'Test notification sent.',
      'about': 'About',
      'app_version': 'App Version',
      'about_app': 'About This App',
      'about_description':
          'A comprehensive Islamic app with prayer times, Quran, Azkar, and more.',
      'language': 'Language',
      'language_arabic': 'Arabic',
      'language_english': 'English',
      'welcome_greeting': 'Peace be upon you',
      'home_intro': 'Track your prayers, read Quran, and maintain daily Azkar.',
      'prayer_times': 'Prayer Times',
      'check_prayer_schedule': 'Check today\'s prayer schedule and Qibla.',
      'browse_surahs': 'Browse surahs and read verses.',
      'morning_evening_azkar':
          'Morning and evening Azkar with tasbeeh counter.',
      'theme_method_notifications':
          'Theme, method, language, and notifications.',
      'try_again': 'Try Again',
      'retry': 'Retry',
      'unable_load_prayer_times': 'Unable to load prayer times.',
      'location_services_disabled':
          'Location services are disabled. Please enable GPS.',
      'location_permission_required':
          'Location permission is required to fetch prayer times and Qibla.',
      'daily_prayers': 'Daily Prayers',
      'location': 'Location',
      'coordinates': 'Coordinates',
      'hijri': 'Hijri',
      'gregorian': 'Gregorian',
      'next': 'Next',
      'in': 'in',
      'next_prayer': 'Next Prayer',
      'am_short': 'AM',
      'pm_short': 'PM',
      'qibla_compass': 'Qibla Compass',
      'qibla_direction': 'Qibla direction',
      'qibla_precision_desc': 'Set your prayer direction accurately.',
      'qibla_correct_direction': 'You are facing the right Qibla direction',
      'rotate_to_qibla': 'Rotate your phone toward Qibla',
      'prayer_list': 'Prayer List',
      'prayer_times_today': 'Today\'s Prayer Times',
      'today_hijri_sample': 'Friday, 15 Ramadan',
      'current_location_cairo': 'Current location: Cairo, Egypt',
      'prayer_times_auto_update':
          'Prayer times are automatically updated based on your location.',
      'change': 'Change',
      'unable_load_prayer_times_connection':
          'Unable to load prayer times. Please check your internet connection.',
      'compass_not_available': 'Compass is not available on this device.',
      'device_heading': 'Device heading',
      'search_surah_hint': 'Search surah by Arabic or English name',
      'unable_load_surahs': 'Unable to load Surahs.',
      'no_surah_match': 'No surah matched your search.',
      'verses': 'verses',
      'text_size': 'Text size',
      'unable_load_verses': 'Unable to load verses.',
      'no_verses': 'No verses available.',
      'azkar_tasbeeh': 'Azkar & Tasbeeh',
      'failed_load_azkar': 'Failed to load azkar data.',
      'no_azkar_found': 'No azkar data found.',
      'tasbeeh_counter': 'Tasbeeh Counter',
      'count': 'Count',
      'reset': 'Reset',
      'no_fixed_target': 'No fixed target count',
      'onboarding_welcome_title': 'Welcome to Islamic App',
      'onboarding_welcome_body':
          'Your companion for daily Islamic practices, prayer times, and the Holy Quran.',
      'onboarding_location_title': 'Enable Location',
      'onboarding_location_body':
          'We need your location to provide accurate prayer times for your area.',
      'onboarding_notifications_title': 'Enable Notifications',
      'onboarding_notifications_body':
          'Get reminders for prayer times and important Islamic events.',
      'back': 'Back',
      'next_btn': 'Next',
      'enable_location': 'Enable Location',
      'enable_notifications': 'Enable Notifications',
      'skip': 'Skip',
      'prayer_reminder_title': 'Prayer Reminder',
      'prayer_reminder_body': 'It is now time for prayer',
      'islamic_app_version': 'Islamic App v1.0.0',
      'search_surah': 'Search for a Surah...',
      'continue_reading': 'Continue Reading',
      'monthly_khatmah': 'Monthly Khatmah',
      'surahs_index': 'Surahs Index',
      'surahs_results': 'Surahs Results',
      'ayahs_search_results': 'Ayahs Search Results',
      'no_ayahs_match': 'No Ayahs match the search',
      'view_all': 'View All',
      'ayah_of_the_day': 'Ayah of the Day',
      'random_ayah': 'Random verse',
      'ayah_day_reference': 'Surah At-Talaq - Verses 2-3',
      'error_loading_ayah': 'Sorry, error loading Ayah',
      'sunrise': 'Sunrise',
      'fajr': 'Fajr',
      'dhuhr': 'Dhuhr',
      'asr': 'Asr',
      'maghrib': 'Maghrib',
      'isha': 'Isha',
      'user_name': 'Ahined Abdullah',
      'user_location': 'Cairo, Egypt',
      'adhan_notifications': 'Adhan Notifications',
      'customize_all': 'Customize All',
      'calc_method_desc':
          'Determine Fajr and Isha angle based on geographical location.',
      'egyptian_general_authority': 'Egyptian General Authority of Survey',
      'appearance': 'Appearance',
      'light_mode': 'Light Mode',
      'dark_mode_on': 'Dark Mode',
      'contact_us': 'Contact Us',
      'contact_us_desc':
          'We are always happy to receive your suggestions to improve the Al-Fajr app experience.',
      'send_message': 'Send Message',
      'logout': 'Log Out',
      'prayer_label_prefix': 'Prayer',
      'current_prayer': 'Current',
      'unable_load_surahs_now':
          'Unable to load surahs right now. Please check your internet connection.',
      'server_connection_error':
          'An error occurred while connecting to the server.',
      'surah_type_meccan': 'Meccan',
      'surah_type_medinan': 'Medinan',
      'search_surah_or_number_hint': 'Search surah or number...',
      'search_juz_hint': 'Search Juz...',
      'last_read': 'Last Read',
      'surah_word': 'Surah',
      'reached_verse': 'Reached verse',
      'completed_percent': 'Completed',
      'goal': 'Goal',
      'read_count_this_month': 'You read',
      'from_total_surahs': 'of total surahs',
      'surahs_tab': 'Surahs',
      'juz_tab': 'Juz',
      'juz_index': 'Juz Index',
      'juz_word': 'Juz',
      'no_juz_match': 'No Juz found',
      'tap_to_read_full_juz': 'Tap to read the full Juz',
      'result_word': 'results',
      'ayah_word': 'Ayah',
      'unable_load_verses_later':
          'Failed to load surah verses. Please try again later.',
      'bookmark_saved_at_verse': 'Bookmark saved at verse',
      'hizb_label': 'Hizb',
      'quarter_hizb_label': 'Quarter Hizb',
      'half_hizb_label': 'Half Hizb',
      'three_quarters_hizb_label': 'Three-Quarter Hizb',
      'quran_title_full': 'The Holy Quran',
      'tap_ayah_to_bookmark': 'Tap any ayah to save a bookmark',
      'juz_info_unavailable': 'Juz information is currently unavailable',
      'previous_surah': 'Previous Surah',
      'next_surah': 'Next Surah',
      'previous_juz': 'Previous Juz',
      'next_juz': 'Next Juz',
      'reader_previous': 'Previous',
      'reader_next': 'Next',
      'surah_info': 'Surah Information',
      'name_label': 'Name',
      'type_label': 'Type',
      'surah_number_label': 'Surah Number',
      'ayah_count_label': 'Ayah Count',
      'no_azkar_in_section': 'No azkar are available in this section right now',
      'muslim_azkar': 'Muslim Azkar',
      'morning_azkar': 'Morning Azkar',
      'after_prayer_azkar': 'After Prayer',
      'evening_azkar': 'Evening Azkar',
      'sleep_azkar': 'Sleep Azkar',
      'morning_azkar_subtitle': 'Starts from Fajr',
      'after_prayer_azkar_subtitle': 'After every prayer',
      'evening_azkar_subtitle': 'After Asr prayer',
      'sleep_azkar_subtitle': 'Before sleeping',
      'zekr_count_unit': 'Azkar',
      'azkar_ayah_of_day_text':
          'Indeed, in the remembrance of Allah do hearts find rest',
      'tasbeeh_phrase_subhanallah': 'Subhan Allah',
      'tasbeeh_phrase_alhamdulillah': 'Alhamdulillah',
      'tasbeeh_phrase_la_ilaha_illa_allah': 'La ilaha illa Allah',
      'tasbeeh_phrase_allahu_akbar': 'Allahu Akbar',
      'tasbeeh_phrase_astaghfirullah': 'Astaghfirullah',
      'tasbeeh_phrase_hawqala': 'La hawla wa la quwwata illa billah',
      'smart_tasbeeh': 'Smart Tasbeeh',
      'reset_all': 'Reset All',
      'repeat_label': 'Repeat',
      'azkar_categories': 'Azkar Categories',
      'search_zekr_hint': 'Search azkar...',
      'no_matching_results': 'No matching results',
      'continue_azkar': 'Continue last azkar',
      'azkar_session_complete': 'Completed — tap to repeat',
      'edit_profile': 'Edit profile',
      'profile_name_label': 'Name',
      'profile_location_label': 'City',
      'profile_invalid': 'Enter a valid name and city.',
      'profile_saved': 'Profile saved',
      'notifications_permission_denied': 'Notification permission was denied.',
      'notifications_enabled_body': 'Prayer reminders are now enabled.',
      'notifications_disabled': 'Prayer reminders are off.',
      'customize_prayer_alerts': 'Customize prayer alerts',
      'contact_message_hint': 'Write your suggestion or issue...',
      'contact_message_invalid': 'Please write a message of at least 8 characters.',
      'contact_email_subject': 'Al-Fajr app feedback',
      'contact_launch_failed': 'Could not open the mail app.',
      'logout_confirm': 'Clear your saved profile name and location?',
      'logged_out': 'Signed out of the profile',
      'cancel': 'Cancel',
      'save': 'Save',
    },
    'ar': {
      'app_title': 'الفجر',
      'home': 'الرئيسية',
      'quran': 'القرآن',
      'prayer': 'الصلاة',
      'azkar': 'الأذكار',
      'settings': 'الإعدادات',
      'display': 'العرض',
      'dark_mode': 'الوضع الداكن',
      'prayer_settings': 'إعدادات الصلاة',
      'calculation_method': 'طريقة الحساب',
      'notifications': 'الإشعارات',
      'enable_prayer_notifications': 'تفعيل إشعارات الصلاة',
      'allow_reminders': 'السماح بتذكيرات الصلوات القادمة.',
      'notification_permission_denied':
          'تم رفض إذن الإشعارات. يرجى تفعيله من إعدادات النظام.',
      'send_test_notification': 'إرسال إشعار تجريبي',
      'trigger_test_reminder': 'إرسال تذكير تجريبي فوري.',
      'test_notification_sent': 'تم إرسال الإشعار التجريبي.',
      'about': 'حول التطبيق',
      'app_version': 'إصدار التطبيق',
      'about_app': 'عن هذا التطبيق',
      'about_description':
          'تطبيق إسلامي شامل لمواقيت الصلاة والقرآن والأذكار والمزيد.',
      'language': 'اللغة',
      'language_arabic': 'العربية',
      'language_english': 'الإنجليزية',
      'welcome_greeting': 'السلام عليكم ورحمة الله وبركاته',
      'home_intro': 'تابع صلاتك، اقرأ القرآن، واستمر في أذكارك اليومية.',
      'prayer_times': 'مواقيت الصلاة',
      'check_prayer_schedule': 'اعرض مواقيت اليوم والقبلة.',
      'browse_surahs': 'تصفح السور واقرأ الآيات.',
      'morning_evening_azkar': 'أذكار الصباح والمساء مع عداد تسبيح.',
      'theme_method_notifications': 'الثيم وطريقة الحساب واللغة والإشعارات.',
      'try_again': 'حاول مرة أخرى',
      'retry': 'إعادة المحاولة',
      'unable_load_prayer_times': 'تعذر تحميل مواقيت الصلاة.',
      'location_services_disabled': 'خدمات الموقع متوقفة. يرجى تفعيل GPS.',
      'location_permission_required':
          'نحتاج إذن الموقع لجلب مواقيت الصلاة والقبلة.',
      'daily_prayers': 'الصلوات اليومية',
      'location': 'الموقع',
      'coordinates': 'الإحداثيات',
      'hijri': 'الهجري',
      'gregorian': 'الميلادي',
      'next': 'القادمة',
      'in': 'بعد',
      'next_prayer': 'الصلاة القادمة',
      'am_short': 'ص',
      'pm_short': 'م',
      'qibla_compass': 'بوصلة القبلة',
      'qibla_direction': 'اتجاه القبلة',
      'qibla_precision_desc': 'حدد اتجاه صلاتك بدقة',
      'qibla_correct_direction': 'أنت في الاتجاه الصحيح',
      'rotate_to_qibla': 'حرّك هاتفك حتى يتجه نحو القبلة',
      'prayer_list': 'قائمة الصلوات',
      'prayer_times_today': 'مواقيت الصلاة اليوم',
      'today_hijri_sample': 'الجمعة، ١٥ رمضان',
      'current_location_cairo': 'الموقع الحالي: القاهرة، مصر',
      'prayer_times_auto_update': 'يتم تحديث المواقيت تلقائياً حسب موقعك',
      'change': 'تغيير',
      'unable_load_prayer_times_connection':
          'تعذر تحميل مواقيت الصلاة. تأكد من اتصال الإنترنت.',
      'compass_not_available': 'البوصلة غير متاحة على هذا الجهاز.',
      'device_heading': 'اتجاه الجهاز',
      'search_surah_hint': 'ابحث عن السورة بالعربية أو الإنجليزية',
      'unable_load_surahs': 'تعذر تحميل السور.',
      'no_surah_match': 'لا توجد سورة مطابقة للبحث.',
      'verses': 'آية',
      'text_size': 'حجم النص',
      'unable_load_verses': 'تعذر تحميل الآيات.',
      'no_verses': 'لا توجد آيات متاحة.',
      'azkar_tasbeeh': 'الأذكار والتسبيح',
      'failed_load_azkar': 'تعذر تحميل بيانات الأذكار.',
      'no_azkar_found': 'لا توجد بيانات أذكار.',
      'tasbeeh_counter': 'عداد التسبيح',
      'count': 'تسبيح',
      'reset': 'إعادة',
      'no_fixed_target': 'لا يوجد عدد محدد',
      'onboarding_welcome_title': 'مرحبا بك في تطبيق الفجر',
      'onboarding_welcome_body':
          'رفيقك اليومي للعبادات ومواقيت الصلاة والقرآن الكريم.',
      'onboarding_location_title': 'تفعيل الموقع',
      'onboarding_location_body':
          'نحتاج موقعك لتقديم مواقيت صلاة دقيقة لمنطقتك.',
      'onboarding_notifications_title': 'تفعيل الإشعارات',
      'onboarding_notifications_body':
          'احصل على تذكيرات بمواقيت الصلاة والمناسبات الإسلامية.',
      'back': 'السابق',
      'next_btn': 'التالي',
      'enable_location': 'تفعيل الموقع',
      'enable_notifications': 'تفعيل الإشعارات',
      'skip': 'تخطي',
      'prayer_reminder_title': 'تذكير صلاة',
      'prayer_reminder_body': 'حان الآن وقت الصلاة',
      'islamic_app_version': 'الفجر v1.0.0',
      'search_surah': 'ابحث عن سورة...',
      'continue_reading': 'استمر في التلاوة',
      'monthly_khatmah': 'الورد الشهري',
      'surahs_index': 'فهرس السور',
      'surahs_results': 'نتائج السور',
      'ayahs_search_results': 'نتائج البحث في الآيات',
      'no_ayahs_match': 'لم يتم العثور على آيات مطابقة للبحث',
      'view_all': 'عرض الكل',
      'ayah_of_the_day': 'آية اليوم',
      'random_ayah': 'آية عشوائية',
      'ayah_day_reference': 'سورة الطلاق - آية ٢-٣',
      'error_loading_ayah': 'عذراً، حدث خطأ في تحميل الآية',
      'sunrise': 'الشروق',
      'fajr': 'الفجر',
      'dhuhr': 'الظهر',
      'asr': 'العصر',
      'maghrib': 'المغرب',
      'isha': 'العشاء',
      'user_name': 'أحمد عبدالله',
      'user_location': 'القاهرة، مصر',
      'adhan_notifications': 'تنبيهات الأذان',
      'customize_all': 'تخصيص الكل',
      'calc_method_desc':
          'تحديد زاوية الفجر والعشاء بناءً على الموقع الجغرافي.',
      'egyptian_general_authority': 'الهيئة العامة المصرية للمساحة',
      'appearance': 'المظهر',
      'light_mode': 'الوضع الفاتح',
      'dark_mode_on': 'الوضع الداكن',
      'contact_us': 'تواصل معنا',
      'contact_us_desc':
          'نسعد دائماً باستقبال اقتراحاتكم لتطوير تجربة تطبيق الفجر.',
      'send_message': 'إرسال رسالة',
      'logout': 'تسجيل الخروج',
      'prayer_label_prefix': 'صلاة',
      'current_prayer': 'الحالية',
      'unable_load_surahs_now':
          'لا يمكن تحميل السور حالياً. تأكد من اتصال الإنترنت.',
      'server_connection_error': 'حدث خطأ أثناء الاتصال بالخادم.',
      'surah_type_meccan': 'مكية',
      'surah_type_medinan': 'مدنية',
      'search_surah_or_number_hint': 'ابحث عن سورة أو رقم...',
      'search_juz_hint': 'ابحث عن جزء...',
      'last_read': 'آخر قراءة',
      'surah_word': 'سورة',
      'reached_verse': 'وصلت إلى الآية',
      'completed_percent': 'تم إنجاز',
      'goal': 'الهدف',
      'read_count_this_month': 'قرأت',
      'from_total_surahs': 'من إجمالي السور',
      'surahs_tab': 'السور',
      'juz_tab': 'الأجزاء',
      'juz_index': 'فهرس الأجزاء',
      'juz_word': 'جزء',
      'no_juz_match': 'لم يتم العثور على أي جزء',
      'tap_to_read_full_juz': 'اضغط لقراءة الجزء كاملًا',
      'result_word': 'نتيجة',
      'ayah_word': 'الآية',
      'unable_load_verses_later':
          'فشل في تحميل آيات السورة. يرجى المحاولة لاحقاً.',
      'bookmark_saved_at_verse': 'تم حفظ العلامة عند الآية',
      'hizb_label': 'الحزب',
      'quarter_hizb_label': 'ربع الحزب',
      'half_hizb_label': 'نصف الحزب',
      'three_quarters_hizb_label': 'ثلاثة أرباع الحزب',
      'quran_title_full': 'القرآن الكريم',
      'tap_ayah_to_bookmark': 'اضغط على أي آية لحفظ العلامة فيها',
      'juz_info_unavailable': 'معلومات الجزء غير متاحة حالياً',
      'previous_surah': 'السورة السابقة',
      'next_surah': 'السورة التالية',
      'previous_juz': 'الجزء السابق',
      'next_juz': 'الجزء التالي',
      'reader_previous': 'السابق',
      'reader_next': 'التالي',
      'surah_info': 'معلومات السورة',
      'name_label': 'الاسم',
      'type_label': 'النوع',
      'surah_number_label': 'رقم السورة',
      'ayah_count_label': 'عدد الآيات',
      'no_azkar_in_section': 'لا توجد أذكار في هذا القسم حالياً',
      'muslim_azkar': 'أذكار المسلم',
      'morning_azkar': 'أذكار الصباح',
      'after_prayer_azkar': 'بعد الصلاة',
      'evening_azkar': 'أذكار المساء',
      'sleep_azkar': 'أذكار النوم',
      'morning_azkar_subtitle': 'تبدأ من طلوع الفجر',
      'after_prayer_azkar_subtitle': 'دبر كل صلاة',
      'evening_azkar_subtitle': 'بعد صلاة العصر',
      'sleep_azkar_subtitle': 'قبل النوم',
      'zekr_count_unit': 'ذكراً',
      'azkar_ayah_of_day_text': 'أَلا بِذِكْرِ اللَّهِ تَطْمَئِنُّ الْقُلُوبُ',
      'tasbeeh_phrase_subhanallah': 'سبحان الله',
      'tasbeeh_phrase_alhamdulillah': 'الحمد لله',
      'tasbeeh_phrase_la_ilaha_illa_allah': 'لا إله إلا الله',
      'tasbeeh_phrase_allahu_akbar': 'الله أكبر',
      'tasbeeh_phrase_astaghfirullah': 'استغفر الله',
      'tasbeeh_phrase_hawqala': 'لا حول ولا قوة إلا بالله',
      'smart_tasbeeh': 'المسبحة الذكية',
      'reset_all': 'إعادة تعيين الكل',
      'repeat_label': 'التكرار',
      'azkar_categories': 'تصنيفات الأذكار',
      'search_zekr_hint': 'ابحث عن ذكر...',
      'no_matching_results': 'لا توجد نتائج مطابقة للبحث',
      'continue_azkar': 'متابعة آخر ذكر',
      'azkar_session_complete': 'اكتملت — اضغط للإعادة',
      'edit_profile': 'تعديل الملف الشخصي',
      'profile_name_label': 'الاسم',
      'profile_location_label': 'المدينة',
      'profile_invalid': 'أدخل اسماً ومدينة صالحين.',
      'profile_saved': 'تم حفظ الملف الشخصي',
      'notifications_permission_denied': 'تم رفض إذن الإشعارات.',
      'notifications_enabled_body': 'تم تفعيل تذكيرات الصلاة.',
      'notifications_disabled': 'تم إيقاف تذكيرات الصلاة.',
      'customize_prayer_alerts': 'تخصيص تنبيهات الصلوات',
      'contact_message_hint': 'اكتب اقتراحك أو المشكلة...',
      'contact_message_invalid': 'اكتب رسالة من 8 أحرف على الأقل.',
      'contact_email_subject': 'ملاحظات تطبيق الفجر',
      'contact_launch_failed': 'تعذر فتح تطبيق البريد.',
      'logout_confirm': 'مسح الاسم والمدينة المحفوظين؟',
      'logged_out': 'تم تسجيل الخروج من الملف الشخصي',
      'cancel': 'إلغاء',
      'save': 'حفظ',
    },
  };

  static String tr(BuildContext context, String key) {
    final languageCode = Localizations.localeOf(context).languageCode;
    final values =
        _localizedValues[languageCode] ?? _localizedValues[_fallbackLanguage]!;
    return values[key] ?? _localizedValues[_fallbackLanguage]![key] ?? key;
  }

  static bool isRtl(BuildContext context) {
    return Localizations.localeOf(context).languageCode == 'ar';
  }
}

extension AppLocalizationContext on BuildContext {
  String tr(String key) => AppLocalizations.tr(this, key);

  bool get isAppRtl => AppLocalizations.isRtl(this);

  TextDirection get appTextDirection =>
      isAppRtl ? TextDirection.rtl : TextDirection.ltr;
}
